### ISSUE TITLE
Social share

### ISSUE THREAD

**Issue by rogeroffer** [Xtraball/Siberian#102]
Social share function is pointing to the mobile website of the app and not to the markets. I opened many times a ticket for this and always closed that will be solved in next update. 7 months later still not solved. And YES all market urls are filled in.

**Comment by Alboorii** [comment]
Go to backoffice > manage > applications > choose your app

Enter app links in Device Information section and try.

**Comment by rogeroffer** [comment]
Ali, probably you never tested it. Is not working even Anders jay Faust told me that it is not working. So is not solved yet

**Comment by Alboorii** [comment]
I saw Anders reply.
Once you click on the mobile app link its take you to the play or app store.

**Comment by rogeroffer** [comment]
Takes you to the mobile website not to the app stores. Tried many times and opened several tickets. Please refer me to an app of you on the app store for testing

**Comment by rogeroffer** [comment]
you are right
but only on mobile not on a pc is redirected to the store

**Comment by Alboorii** [comment]
Yes its work on mobile, Because its detect which platform is :).

**Comment by dbyzero** [comment]
@Alboorii thank you very much for your intervention.
We already add it on our bug tracker, we need to improve this part.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?
