### ISSUE TITLE
remove the bad tags

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#11]
There is a tag problem: https://github.com/Xtraball/Siberian/releases, can you remove the bad tag?
an hour ago v4.13.16    280d722 zip tar.gz
a day ago 4.13.14    5017fa9 zip tar.gz
23 hours ago v4.13.15    bc2b07e zip tar.gz
a day ago v4.13.14    e04956c zip tar.gz
9 days ago 4.13.13    e662e7f zip tar.gz
9 days ago v4.13.13    f7ce71f zip tar.gz 
etc

4.13.13 and 4.13.14 have double tags

@SiberianCMS @dbyzero @Slicit @LikoV2

**Comment by Slicit** [comment]
We don't use Github releases yet, so you can't rely on these, thanks.

**Comment by userdevel** [comment]
If you do not use, why there are?

**Comment by userdevel** [comment]
Bad tags have been removed by team, thanks.
