### ISSUE TITLE
a lot of double commits for one

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#12]
There are a lot of double commits for one since November 9th 2017:

chore: add ionic & resources
https://github.com/Xtraball/Siberian/commit/f2d7e84726512f9c626f2f8f1e3308e909a33f0e
@Slicit
Slicit committed on 9 Nov 2017

chore: add ionic & resources
https://github.com/Xtraball/Siberian/commit/19f90d280d39d975612600880983c3a026ad33a0
@Slicit
Slicit committed on 9 Nov 2017

https://github.com/Xtraball/Siberian/commits/master?after=bc2b07edffec0af40425187a7a79fd8d5aa2dcdd+874

Why?

There is a problem?

It is possible to clean it?

@SiberianCMS @dbyzero @Slicit @LikoV2

**Comment by Slicit** [comment]
Nope, these are part of our CI lane, these are automatically built with our tools, some files & commits are automatically generated on release tag commits, and we can't remove them as they are used on our tools.

**Comment by userdevel** [comment]
It is normal when one commit is doubled?

**Comment by Slicit** [comment]
It's not "doubled" these are automated commits, so the names are automated too and are duplicated around each release.
The prefix `chore` is meant for `this is an informational commit, ignore me.`

**Comment by userdevel** [comment]
It was a example... We need to ignore all?

Next were: 
feat: app, cli import
https://github.com/Xtraball/Siberian/commit/3cbf8accffbd6406f8f4ee38c664883cad043c62
@Slicit
Slicit committed on 9 Nov 2017

feat: app, cli import
https://github.com/Xtraball/Siberian/commit/f9f242ac90c98f3e34185eae94018852649c726e
@Slicit
Slicit committed on 9 Nov 2017

etc...

**Comment by userdevel** [comment]
There is a problem in commit job... please change to be perfect.

Please note that there are not problems like this in all other projects in the World.
-> No double (and more), no commit version problem, no release tag problem...

**Comment by Slicit** [comment]
Seriously? 
What do you mean really? 
these are commits why would you ignore them? If you are forking Siberian just follow ALL the master commits, they are ALL necessary.

Otherwise I don't see your point.

**Comment by userdevel** [comment]
"The prefix chore is meant for this is an informational commit, ignore me." <-- ignore me

**Comment by Slicit** [comment]
If you want to track versions, only tags with prefix "vX.X.X" are valids.

**Comment by Slicit** [comment]
And when I said "ignore me" it's part of the CI, so you don't "skip" the commit, but rather ignore what it does, as it's automatically builds part of the release.

**Comment by userdevel** [comment]
Please read all my remarks about:
- Double (and more) commit since november 2017 for once.
- Several version commit name, we are lost...
- Do not create bad tags...

Example:


- chore: add ionic & resources
-- https://github.com/Xtraball/Siberian/commit/f2d7e84726512f9c626f2f8f1e3308e909a33f0e
-- https://github.com/Xtraball/Siberian/commit/19f90d280d39d975612600880983c3a026ad33a0
- feat: app, cli import (same)
-- https://github.com/Xtraball/Siberian/commit/3cbf8accffbd6406f8f4ee38c664883cad043c62
-- https://github.com/Xtraball/Siberian/commit/f9f242ac90c98f3e34185eae94018852649c726e
- chore: resource archives.
-- https://github.com/Xtraball/Siberian/commit/6fc501cb20950c9c1ac02a9cb7be1e2a4a70b6be
-- https://github.com/Xtraball/Siberian/commit/c070441ab2ee25d6d1e6d019e95a885db38b25f9
-- https://github.com/Xtraball/Siberian/commit/f62662cc0d6a5d9ae585ecb7517e195edc903917
- Merge branch 'release/4.13.12' into develop
-- https://github.com/Xtraball/Siberian/commit/bc834c03841897c705193e21cfd3d78e363c1cc6
-- https://github.com/Xtraball/Siberian/commit/91cc5db9923aa6391c963a0c970050ae1fa120f0
- v4.13.17
-- https://github.com/Xtraball/Siberian/commit/136420435cbcefcd7bafb52a25a6b01dc3308b49
-- https://github.com/Xtraball/Siberian/commit/312a2f091b05e8618c42b4deee8641c451c8f6d8

2 and 1 different:
- v4.13.14
-- https://github.com/Xtraball/Siberian/commit/44a7ee6168466727e0d031bacafdaa154b28def3
-- https://github.com/Xtraball/Siberian/commit/bdf939ae2ed414fba561d84a693c1a1c1205b3ff
-- https://github.com/Xtraball/Siberian/commit/e512dda5fc9a8e34c6ec12ded6c09f49e93b056e

Tag already created but it is not finish we are ok?
v4.13.17 -> https://github.com/Xtraball/Siberian/releases

**Comment by userdevel** [comment]
All my remarks are here for be really perfect... not to bother you!

**Comment by Slicit** [comment]
Yes, but perfect generally leads to never, so sometimes, upon some release there is a double commit with the same name version, but the tag is unique.

**Comment by userdevel** [comment]
Recall : https://github.com/Xtraball/Siberian/issues/11
Thanks for the removal of bad tags!

Hope no new double (or more) commits and bad commit version name ^^

**Comment by Slicit** [comment]
Don't hope that much ;)

**Comment by userdevel** [comment]
If your git installation is perfectly configured, no double (and more) there will be ;)

After it is a question of push too...
http://rogerdudler.github.io/git-guide/

For commit name, it is a logic: the version commit name is the last commit for the version (+ release tag)
