### ISSUE TITLE
QR Code Scanner - Limitations or Bug?

### ISSUE THREAD

**Issue by Kaharian** [Xtraball/Siberian#136]
Hi Team, I was stress testing the QR Code Scanner feature of Siberian and have compared it to other FREE Stand-alone QR Scanners...

What I have noticed is that our Siberian QR Scanner has problems decoding QR email, QR SMS, QR Location, QR call, and it's only okay on the basic QR link (Opens up a link), and QR Text (Just the basic text) 

On QR vCard, it just opens as text details not in a ready format to be added to your contacts, unlike other FREE QR Scanners... same thing happens on QR Wifi... just text output but cannot connect right away to the internet, again... unlike other FREE QR Scanners.

The QR Scanner is a very useful tool and hopefully we can have some improvements on this down the line. I don't know if this is a bug or just a limitation of our QR feature.

Yes, we can always use external QR scanners but having our own and built-into apps will be much better.
Just sharing what I have noticed. Thanks!

![4c](https://cloud.githubusercontent.com/assets/25316236/22301724/132e92e6-e33d-11e6-88ff-f44abb9bcea2.jpg)
![1a](https://cloud.githubusercontent.com/assets/25316236/22301725/1334271a-e33d-11e6-8f55-50e1ce2b6ba8.jpg)
![2a](https://cloud.githubusercontent.com/assets/25316236/22301726/13350f40-e33d-11e6-9aef-7ea4f717b4c7.jpg)
![3b](https://cloud.githubusercontent.com/assets/25316236/22301727/1336d4b0-e33d-11e6-9cf0-4c88d578fb01.jpg)

**Comment by PofMagicfingers** [comment]
This is a limitation not a bug ;-)

**Comment by Kaharian** [comment]
Okay... :) So... can we expect to at least match all the other FREE QR scanners? It would be nice to scan a geolocation and immediately show us the Google maps... Or at least scan an email and immediately it will be ready for you to send, scan a wifi and you are ready to connect, scan a vcard and it will be ready to be added to your contacts, scan a phone number and it will automatically be dialed and ready to be called... etc.

Other FREE QR Scanners did it, our platform is way better that the others so I think this can also be done.

Cheers everyone!

Regards,

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?

**Comment by SiberianCMS** [comment]
The feature codescan is not a "generic" code scanner, it's meant to scan codes MADE for the apps, within the apps directly.

So for now, no changes on that, if code is not for app, it will be displayed as text, still read
