### ISSUE TITLE
FORMS - Addition of "My Account" as one of the Field Options

### ISSUE THREAD

**Issue by Kaharian** [Xtraball/Siberian#138]
When I was analyzing the FORM Module and playing around with it... I thought it could be a really nice feature by just adding one more field option... the "MY ACCOUNT".

Most of the forms that I tried to make require Names, Email, telephone etc...
With this, We can help the user save time in filling out forms because his/her details are already there via "My Account"

And also through this, we will already know for sure who sent that form... Because if we just created Fields like, NAME; Email, etc... some users can play around and just write any other names or email. But if we include 'My Account", those worries will be erased.

Imagine what kinds of forms we can make if we include "My Account"

- - Order Form
- - Service Request Form
- - Attendance Form (With Geo-location plus Time stamp this can actually be a Time Card of sorts)
- Application Form
- Survey Form
- Client Information Sheet Form
- Credit Application Form
- Plus a lot of other forms...

With 'My Account" the forms we are creating will be more reliable and more secured because those were sent by logged in users, who are identifiable.

![forms](https://cloud.githubusercontent.com/assets/25316236/22304216/984e7afe-e347-11e6-93e1-5cdd597bdcfc.jpg)

**Comment by PofMagicfingers** [comment]
In the [survey module](https://extensions.siberiancms.com/downloads/surveys-get-rich-feedbacks-from-users/) exported CSV data contains users emails. This is not present in form feature though.

**Comment by clifton11221** [comment]
I agree... This would drastically improve the module and open opportunities for apps.

**Comment by Kaharian** [comment]
Hi, Thanks clifton11221... you got what I was trying to explain... Just one more extra field option which is already available and the Forms Feature will fly!

Actually, it doesn't have to be an extra field... maybe just a check button asking "Would you like to turn on "My Accounts" for this form?

I hope this gets the attention of Siberian...

**Comment by dbyzero** [comment]
Currently, we are focused on debugging. When all major bugs will be fixed, we will start to implement good ideas like yours.

**Comment by Slicit** [comment]
Form have been reworked and now take in logged in customer & save results in database.
