### ISSUE TITLE
Remove the bad tags again

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#16]
There is a tag problem: https://github.com/Xtraball/Siberian/releases, can you remove the bad tag?
4.14.13 ef3bf67
v4.14.13 0032b98
v4.14.13-beta.1 b67e19e
4.14.12 b13d40b
v4.14.12 19489c8
4.14.11 126a52a
v4.14.11 672e8f7
v4.14.10 8d30503
4.14.10 ea258d9

@SiberianCMS @dbyzero @Slicit @LikoV2 @alexyves

**Comment by LikoV2** [comment]
Will do when we have time.
