### ISSUE TITLE
Additional image sizes

### ISSUE THREAD

**Issue by herobe** [Xtraball/Siberian#169]
Hello, at this moment working on the previewer app. 
But is also valid for regular apps 
In the different startup dimensions there are some missing. 
I will now add them manually in the ipa package using xcode. 
Maybe add additional input screens to upload missing screensizes : 
2208 x 1242 
2048 x 1536 
1024 x 768
768 x 1024 

![screen shot 2017-02-10 at 12 28 47](https://cloud.githubusercontent.com/assets/25324997/22825283/97517222-ef8c-11e6-88c5-d0021b63b4d1.png)

Files are stored in folder (IOS) : AppsMobileCompany/Resources

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?

**Comment by SiberianCMS** [comment]
On iOS we only make use of this image format

Default@2x~universal~anyany.jpg

Because it works on all devices, and all orientations, that way we only embed a single asset (which is already heavy) inside the app, and our uploader/editor for this image is made especially to check that.
