### ISSUE TITLE
Question about double files / folders (cleanning code)

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#17]
There are double files/folders:
- Source?
-- https://github.com/Xtraball/Siberian/tree/master/ionic/platforms
- Used?
-- https://github.com/Xtraball/Siberian/tree/master/siberian/var/apps/ionic

Examples:
- 1
-- https://github.com/Xtraball/Siberian/tree/master/ionic/platforms/android
-- https://github.com/Xtraball/Siberian/tree/master/siberian/var/apps/ionic/android
- 2
-- https://github.com/Xtraball/Siberian/tree/master/ionic/platforms/ios
-- https://github.com/Xtraball/Siberian/tree/master/siberian/var/apps/ionic/ios
- 3
-- https://github.com/Xtraball/Siberian/tree/master/ionic/platforms/browser
-- https://github.com/Xtraball/Siberian/tree/master/ionic/platforms/browser/www
-- https://github.com/Xtraball/Siberian/tree/master/siberian/var/apps/browser

It will be better to use only one (with all) and remove double folders/files.

After it is a question of code for have the good folder...

I will update this ticket for all folders...

Same files...
- 0
-- Siberian-release-4.15.0\resources\ionicons\scss
- 1
-- Siberian-release-4.15.0\ionic\platforms\android\app\src\main\assets\www\lib\ionic\scss\ionicons
-- Siberian-release-4.15.0\ionic\platforms\android\app\src\main\assets\www\lib\ionic\scss\ionicons\scss
- 2
-- Siberian-release-4.15.0\ionic\platforms\browser\www\lib\ionic\scss\ionicons
-- Siberian-release-4.15.0\ionic\platforms\browser\www\lib\ionic\scss\ionicons\scss
- 3
-- Siberian-release-4.15.0\ionic\platforms\ios\www\lib\ionic\scss\ionicons
-- Siberian-release-4.15.0\ionic\platforms\ios\www\lib\ionic\scss\ionicons\scss
- 4
-- Siberian-release-4.15.0\ionic\www\lib\ionic\scss\ionicons
-- Siberian-release-4.15.0\ionic\www\lib\ionic\scss\ionicons\scss
- 5
-- Siberian-release-4.15.0\siberian\var\apps\browser\lib\ionic\scss\ionicons
-- Siberian-release-4.15.0\siberian\var\apps\browser\lib\ionic\scss\ionicons\scss
- 6
-- Siberian-release-4.15.0\siberian\var\apps\ionic\android\app\src\main\assets\www\lib\ionic\scss\ionicons
-- Siberian-release-4.15.0\siberian\var\apps\ionic\android\app\src\main\assets\www\lib\ionic\scss\ionicons\scss
- 7
-- Siberian-release-4.15.0\siberian\var\apps\overview\lib\ionic\scss\ionicons
-- Siberian-release-4.15.0\siberian\var\apps\overview\lib\ionic\scss\ionicons\scss
- 8
-- Siberian-release-4.15.0\siberian\var\apps\browser
-- Siberian-release-4.15.0\siberian\var\apps\overview

**Comment by Slicit** [comment]
You don't get it after all this time? This repository includes development sources & pre-built sources for convenience, so yes some files are duplicated.
--
If you get into the developer documentation, you'll find that you have to work on "ionic" files, then using the build tools, the files will be compiled/copied to the right place.

**Comment by Slicit** [comment]
The project is already quite complex, and most of the dependencies are already forked, doing so will add another layer of complexity sadly, it's easier to maintain this way.
