### ISSUE TITLE
Save the form and booking entries in mysql tables

### ISSUE THREAD

**Issue by herobe** [Xtraball/Siberian#176]
This could allow analysis of entered data and allow smart marketing. 
for ex. if someone did a booking at a certain venue 
we could send a push message based on his booking for another venue or same venue. 

-> so if mail is sent save data to mysql table 
will also try to find this.

**Comment by herobe** [comment]
mysql addition has to be done in app/sae/modules/Form/controllers/Mobile/ViewController.php

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?

**Comment by Slicit** [comment]
For was rebuilt and is now saving results in DB.
Nothing for Booking yet.
