### ISSUE TITLE
Form Module Enhancement

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#179]
A good addition would be adding Logic Fields to the Forms module.  This would enable admins to create really good forms and open the door to other additions that could be added to an app.

For example:

If the field was CITY

We can have a Logic field that IF "City" = XXX 

Then display
"123"
"456"
"789"

It can work similar to the Logic fields that you have in the Quiz module.

**Comment by dbyzero** [comment]
Good idea

**Comment by Slicit** [comment]
Form will never have "logic fields" it is in the Quiz module.

Form will remain a simple form.
