### ISSUE TITLE
Going back to app from the webpage that opened through the link feature

### ISSUE THREAD

**Issue by arbindbhagat** [Xtraball/Siberian#19]
In the older version, there was a way to go back to the app from the website linked through the "link" feature. In the latest version, there is no way to go back to the app from the webpage, other than using the device back button.

The device's back button is not always a good option. For example, if you link a website where users need to go to purchase a product (multi step as add-to-cart, checkout, payment, etc), and after making the payment, the user can't go back using the device back button.

**Comment by arbindbhagat** [comment]
It should be easy to implement. It looks like, Siberian can simply add a "close icon (red)" on the top right of the in-app-browser, and call the close function as mentioned here:
http://content.screencast.com/users/Arbind_Bhagat/folders/Jing/media/c6ad554d-a779-448e-bc25-c1bf549003f3/2016-05-26_0357.png

Source: http://ngcordova.com/docs/plugins/inAppBrowser/

**Comment by lampela** [comment]
Hi - this issue is still open. IMHO it's a critical bug, because you have to close the app all together and start over if you click the link. Shouldn't be that way of course.

**Comment by SiberianCMS** [comment]
We are currently fixing it. You will have choice to open link in fullscreen (without navpanel) or with nav pannel.

**Comment by arbindbhagat** [comment]
It has been around 4 months now. Has there been any update to this?

**Comment by dbyzero** [comment]
We aware about the issue, it will be assign to a dev asap.

**Comment by rivman** [comment]
There is no way that links open in phone default browser ? 80% of the sites that open in the build-in browser break into pieces, when the same site is shown correctly in phone browser (chrome ou safari), I mean responsive menus and content. It seems that CSS or scripts presents in sites can't measure the screen while in build-in browser.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?

**Comment by lampela** [comment]
IMHO this issue is fixed.

**Comment by SiberianCMS** [comment]
Not relevant and/or already fixed.
