### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/Siberian#193]
Hey guys,

If you let the App open in the background during a certain moment and reopen it, message "you have gone offline" appears. I only tested for Android. For info, I did not activate the Offline mode.

**Comment by dbyzero** [comment]
What a "certain moment" mean ? 1-2 minutes or few hours ?

May be you was offline for a very short period and application trig the new state.

**Comment by arthurkai** [comment]
1-2 minutes.

**Comment by dbyzero** [comment]
Ok thanks, we will check it, may be do the offline check only in foreground.

**Comment by amjadhadi** [comment]
I have same issue I have wait for 10 min and I got "you have gone offline" many times

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?
