### ISSUE TITLE
Register in my account and i.e. fan wall

### ISSUE THREAD

**Issue by grafixpress** [Xtraball/Siberian#196]
It would be very useful to have the possibility to disallow self registration.
Normally in CMS you can select between
1 self registration
2 registration has to be approved by admin
3 Only manual registration by admin.
This can help to prevent spammers etc. to register in Fan Wall etc. etc.

For the time being is there a way to delete the registration part in login forms via CSS?

**Comment by dbyzero** [comment]
CSS will not stop bot spammer. But you can disable self registration by editing file : 

app/[pe|mae|sae]/design/desktop/flat/template/admin/account/login.phtml

I add enhancement to bug tracker thx.

**Comment by dbyzero** [comment]
Sorry my bad I think you spoke about editor. It will not works for mobile application.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?

**Comment by Slicit** [comment]
Since 4.16.0 you can now disable `self-registration` in  Apps

Open the `My account` feature & un-tick the option.
