### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by arthurkai** [Xtraball/Siberian#209]
Hi Guys,

My Siberian Config : 
PE 4.8.12.4
Language : English
Time Zone : Asia Bangkok (GMT+7)

Time Zone translation error : Language is English but country list is in Thai. See attached pic.

![timezone](https://cloud.githubusercontent.com/assets/19501632/23499085/3e516750-ff5d-11e6-9da5-e66afb3632f9.jpg)

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?

**Comment by Slicit** [comment]
@userdevel if you want to check for issues this github is not relevant anymore

This is the correct one.

https://github.com/Xtraball/Siberian

For this "issue", this section is to be removed/replaced soon, so will be completely changed.

**Comment by SiberianCMS** [comment]
Timezones are inherited from the very very very old core framework "Zend Framework 1" and while, during a time we were able to update the data files for the territories & locales, this is not possible anymore.

We will have to stick with the few non-working ones with Siberian CMS as long as we do not change the Core framework
