### ISSUE TITLE
Remove bad tags again (a new new new time)

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#22]
People are always lost with multiple tag versions;

v4.15.15
 dd39855

v4.15.14
 b4e26c0

4.15.14
 d3c2914

4.15.13
 37e8d0c

v4.15.13
 ea4850f

4.15.12
 403829b

v4.15.12
 ffa3407

4.15.11
 ea04673

v4.15.11
 a0e2964

v4.15.10
 b408225

4.15.9
 7ee2134

v4.15.9
 33938d6

4.15.8
 a036f08

v4.15.8
 dfcbb4c

4.15.7
 41898b0

v4.15.7
 79bdbe7

4.15.6
 9427ce1

v4.15.6
 968d0a5

4.15.5
 f0284fa

mark-pre-update <---------- what pre-update?
 019f1b9

v4.15.5
 914ff48

4.15.4
 082fdb5

v4.15.4
 9bb0b5f

**Comment by Slicit** [comment]
`People are always lost with multiple tag versions;` or you are lost? 

As said previously, the automated CI build script tags twice with & without prefix (v) and so on, maybe if we change our CI scripts this will be gone, we won't just manually fix all tags, consider `vX.X.X` the correct tags
