### ISSUE TITLE
newswall issue

### ISSUE THREAD

**Issue by Liamam** [Xtraball/Siberian#232]
Hello 
The layout of the newswall wall always get rid of text. If you have a long headline it just cuts off. Also if you want to use the last design (the one with the different sized blocks a rogue 1 appears in the box before the headline - again very annoying.

**Comment by krypt3d** [comment]
Might I add its the same for push notifications? I understand push messages in their nature are not long, however there should be a way to have bit more characters.  Therefore users can see these messages at a later date as well inside the application. 

Or maybe have them removed fully from saving inside the app.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?

**Comment by Slicit** [comment]
The NewsWall will have a complete refreshed v2 in 4.17.0 early July

Thanks.
