### ISSUE TITLE
Custom Page Module - Enhancement: Center Align Image Option

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#233]
On the Custom Page module, when inserting an image in the Text box, there is an option to Left and Right align images.  However, centering images is not available.  Please add this additional option.

Also, only one image can be inserted into the Text box.  Can this be changed?

SIDE NOTE: I want to simply add a small rating image on the Custom page (centered) but the option is not available. I can use Cover Image but then the image is too large.  The Image button places the image in a gallery so that doesn't work...  If the "Center" align image option was there then problem solved.

**Comment by SiberianCMS** [comment]
Let's see that!

**Comment by SiberianCMS** [comment]
![Screen Shot 2021-09-01 at 17 24 01](https://user-images.githubusercontent.com/7977082/131699280-39e03dbf-fef2-4b2f-8e12-31b4b00f3891.png)
![Screen Shot 2021-09-01 at 17 25 44](https://user-images.githubusercontent.com/7977082/131699282-7a219a73-f8cb-4347-80cc-b27672a98252.png)

Will be released in 4.20.17
