### ISSUE TITLE
Forms Module Enhancement: Signature Field & Save As PDF

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#235]
Two good additions to the Forms module would be having the option of adding a "Signature" field and an option to "Save As PDF".

The Signature field would enable the app user to sign their name on the phone's screen.

The "Save As PDF" option would be enabled by the app admin.  If enabled, the form results would be emailed to the app admin as a pdf attachment, in addition to how the results are currently emailed to the app admin.

Both additions would enable app admins to create some really good application forms, signature delivery forms, etc.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?

**Comment by SiberianCMS** [comment]
If ever done, that will be inside Forms v2 feature.
