### ISSUE TITLE
Various Chat Module Issues

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#236]
These aren't necessarily bugs but below are a number of issues with Chat module:

**CAN'T FIND PEOPLE TO ADD AS A FRIEND**
Currently there's no way to search for a member's name when attempting to add them as a Friend. You could search for their Nickname and email address (or click their name in a Chat room) which are good options but the search query should also include the (first/last) name they used when they registered.

The reason being, if a person registers for Chat but doesn't chat in a Chat room, there isn't a way to find them if you don't know their Nickname or email (in 2017 nobody knows someone else's email address).

Considering that someone could put anything as a Nickname, there's no way to find people to add them.  An example is Facebook... It's easy to find people because you can search for their name.

I created private Chat app for a client to use with his family and friends.  Even though only people they personally know use the app, nobody can find anyone to add them as a friend.  Finding and adding Friends should very easy to do all across the board.

 

**NO MESSAGE WHEN A FRIEND CAN'T BE FOUND**
When searching for a member to add them as a Friend, if the search query can't find the text entered in the search box, the box simply disappears. It should give a message stating that the Friend couldn't be found (or some other verbiage).  Currently, the app user is left wondering what's going on.

**NO OPTIONS TO DISABLE PRIVATE CHAT OR PRIVATE ROOMS**
The app admin doesn't have any control over their Chatrooms because there isn't any options to Enable/Disable private chat or private rooms.  Adding these options would allow us to create Chat apps for people that want a chat app without the secrecy (workplaces, clubs, school projects, etc).

**Comment by Slicit** [comment]
It's a paid module, we don't handle improvements/support here.
