### ISSUE TITLE
PDF error on ORDER

### ISSUE THREAD

**Issue by euroonesistemi** [Xtraball/Siberian#242]
When you make order with multiple Optrions, the pdf generated is wrong.
Email is ok, but pdf not.
Big problem if you print automatic PDF for order.
Best regrad.
i attach photo.
MAE ver 4.9.1
![photo_2017-03-21_11-13-40](https://cloud.githubusercontent.com/assets/1251660/24142668/8847436a-0e27-11e7-9c09-fe69686b968a.jpg)
![photo_2017-03-21_11-13-46](https://cloud.githubusercontent.com/assets/1251660/24142674/8da328e2-0e27-11e7-8359-049d6d0a815c.jpg)

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?
