### ISSUE TITLE
Links Module Bug:

### ISSUE THREAD

**Issue by glopr** [Xtraball/Siberian#246]
When I try to insert a simple link that calls Android Media Player (any media player installed such as default Android Player, VLC, MX Player, etc) with a "m3u8" url, the following error display on app: http://prntscr.com/eojewn (see screenshot). I just want to open the link to play a live streaming video.

I've tried open this link in source code, custom page, and links module, all redirects to same error page/code.

Not tested on iPhone, if anyone can test and confirm any issue will be helpful.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two year?
