### ISSUE TITLE
Link Module (web protocol)

### ISSUE THREAD

**Issue by glopr** [Xtraball/Siberian#247]
if I want to use rtsp:// instead http://, the link module always force use http:// before saving link. I suggest to improve the link module adding a dropdown list with most common web protocols (http, https, ftp, rtsp, etc.)

**Comment by dbyzero** [comment]
Is it the reason of your ticket #246 ?

**Comment by glopr** [comment]
Similar issue but a little different. Ticket #246 refers to a link with a file extension at the end of the link (I tried with .m3u8 only, not sure if other extension such as pdf, exe, zip, etc have same issue). If I enter this link http://api.new.livestream.com/accounts/5730046/events/2966225/live.m3u8 it's supposed to call the android media player in order to play the video.

Ticket #247 refers to a link that start with a different protocol that isn't the standard http://
The issue is similar because I want to play a streaming file but the link format is different in both tickets. Ticket #246 use a link that play a HLS video (m3u8 / Android HTTP format) and ticket #247 use a link that play videos in Android RTSP, both formats are standards for Playing live video on android devices.

**Comment by glopr** [comment]
You can test m3u8 link on https://www.hlsplayer.net/ and/or opening this link in your Android Device with a standard browser (May need MX Player or VLC Player installed on your phone).

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two year?
