### ISSUE TITLE
Links Module: URL with file extension

### ISSUE THREAD

**Issue by glopr** [Xtraball/Siberian#248]
If I want to make a direct download link using the custom link button under links module and it contains a url with file extension such as .apk, the link doesn't open the file to download it.

**Comment by herobe** [comment]
@glopr try to tweak the js in /app/app/sae/design/desktop/siberian/js/ckeditor/config.js 
at your own risk ! 
at the end of the script the stripping of the link is done

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two year?
