### ISSUE TITLE
offline mode products

### ISSUE THREAD

**Issue by wouter76** [Xtraball/Siberian#269]
Hi,

I found out that when using the offline mode for products only the last product is shown in the app in a offline situation where not yet any other product is shown.

The problem is caused by a problem in the `getFeaturePaths` function in the `Catalog_Model_Category` class. The function loads the products and then loops the products to creates the params for the path, but the path creation occures outside the loop causing only the last product to end up in the offline cache list.

I suggest change the function to:

```
public function getFeaturePaths($option_value) {
        if(!$this->isCacheable()) return array();

        $paths = array();
        $paths[] = $option_value->getPath("findall", array('value_id' => $option_value->getId()), false);

        if($uri = $option_value->getMobileViewUri("find")) {

            $products = $this->getProducts();
            foreach ($products as $product) {
                $params = array(
                    "value_id" => $option_value->getId(),
                    "product_id" => $product->getId()
                );
                $paths[] = $option_value->getPath($uri, $params, false);
            }

            //$paths[] = $option_value->getPath($uri, $params, false); // moved into foreach loop
        }

        return $paths;
    }
```

**Comment by dbyzero** [comment]
Thank you for the report we will check it asap !

**Comment by Slicit** [comment]
Can you create a pull request for this ? thank you.

**Comment by userdevel** [comment]
@wouter76, @Slicit, @LikoV2: Any news after two year?
