### ISSUE TITLE
Mcommerce and Custom Profile Module

### ISSUE THREAD

**Issue by portalidea** [Xtraball/Siberian#278]
Mcommerce and the Custom Profile Module. 
A user login into app and compile additional fields in Custom Profile Module.
I'd like that when a user makes an order...the order data must be filled with Custom Profile data, and the mail with the order details must have Custom profile data.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after two year?

**Comment by SiberianCMS** [comment]
M-commerce is due for a complete overhaul.

Closing.
