### ISSUE TITLE
Mcommerce - Add Custom Field(s)

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#283]
Very often I want to use the Mcommerce module for an app but I can't because someone wants a simple field added to the order (example: Delivery Notes, Pick-up Time, Name On Cake, etc) but there's no way to do this.  

Currently there are 4 pre-built fields to use (Birthday, Phone Number, etc).  However, there should be an option to add a custom field (or two).

**Comment by portalidea** [comment]
It's a very important Enhancement. I've the same problem

**Comment by clifton11221** [comment]
At the very least I think a memo field with the option to title it whatever we want would help.

**Comment by bluesnap-rock** [comment]
Yes 100% agree we need custom fields , so many different variations of online shops this would make it easier for app owners to add specifics to their Mcommerce. Please please add guys 👍

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after two year?

**Comment by Anais527** [comment]
Up !!!

**Comment by SiberianCMS** [comment]
As M-Commerce is due for a complete overhaul, we will not do this.
