### ISSUE TITLE
Mcommerce - Add Thumbnail and Layout Options

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#290]
**THUMBNAIL OPTION**
Currently, there isn't an option to add a thumbnail image to be used as the image in the list view of the Mcommerce product categories.  

The module use the same image for the list view as it does for the category cover.  Since the aspect ratios are different, the images in the list look distorted and not professional. 

Adding the ability to upload a separate "thumbnail" image for the list view would fix the problem.

See below:

![design_01](https://cloud.githubusercontent.com/assets/21089972/25765343/94706b7e-31ba-11e7-8932-96064adffe00.png)

**LAYOUT OPTIONS**

There is only one "list" layout option for the product categories... The list view looks very outdated and prevents the app from looking modern.  Adding additional layout options would help tremendously.  You can add similar layout design options that are available for the RSS module.

![design_02](https://cloud.githubusercontent.com/assets/21089972/25765351/9a98d8c4-31ba-11e7-9cb3-f7222c1fb60b.png)

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after two year?

**Comment by SiberianCMS** [comment]
M-Commerce is due for a complete overhaul, not doing so.
