### ISSUE TITLE
Clear chat

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/Siberian#292]
Is there no way to clear a chat. Not leave room. But if you have friends in manage friends and chst to them....is it not possible to then clear that chat?

**Comment by clifton11221** [comment]
I'm not aware of the option but it would definitely be a welcomed (and needed) addition.

**Comment by krypt3d** [comment]
Yes it would be nice feature to have to be able to clear old chat or at least parse

**Comment by Slicit** [comment]
It's a paid module, we don't handle improvements/support here.
