### ISSUE TITLE
Audio Module: RSS Files Takes An Extremely Long Time To Play

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#294]
When utilizing the RSS option, the audio tracks takes an extremely long time to play.  It takes so long that you think that it's not working.

I tried various RSS feeds and all have the same issue.  Here are two examples to test (from different feeds):

http://feed.mindfulnessmode.com/feed/
http://www.spreaker.com/show/1570677/episodes/feed

**Comment by clifton11221** [comment]
Please note that there's no delay when you listen to the podcast in the app simulator (in Siberian).  However, when you demo the app in the App Previewer or use the live app then the delay occurs.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after two year?

**Comment by SiberianCMS** [comment]
As long as we will not add a Codec SDK, there will always be player issues of any kind.

Adding a Codec SDK is approx. 50MB in size increase for APK, so we are balancing it for the future player, and maybe will have to make it optional, which by the way makes the build more complex.
