### ISSUE TITLE
Chat add friend notification

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/Siberian#295]
We could do with a push notification to the user when someone requests them as a friend?

**Comment by PofMagicfingers** [comment]
This could lead to spam issues... We'll think about it.

**Comment by clifton11221** [comment]
Yes, please add this feature.  The app users need to know when there's activity...  This will keep them engaged.

No different than getting a Notification on FB, Instagram, etc when there's activity.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after two year?

**Comment by Slicit** [comment]
It's a paid module, we don't handle improvements/support here.
