### ISSUE TITLE
Locate button in contact page

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/Siberian#300]
The locate button in the contact page (not custom page) opens a map, but doesn't show directions/navigation like the custom page locate button. I think this is something we could do with because the email button in the contact page opens a contact form so this part of the app is better for contacting rather than a custom page.

**Comment by clifton11221** [comment]
I think the email button on the custom page should open a contact form as well.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after two year?
