### ISSUE TITLE
addSimpleImage doesn't populate the form when used in a layout option form

### ISSUE THREAD

**Issue by lsmod** [Xtraball/Siberian#306]
Image added and got display well just after being uploaded but later on when you reload the page link breaks (src: /images/application592c124339a62.jpg). 
And From the app perspective the image field return only the filename not the path to it (had to add /var/tmp/ in front of it).

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after two year?

**Comment by Slicit** [comment]
You can now user `Feature::registerDataProcessorForLayout([args...])`

To add a callback on `Layout form option save` to manually process your images ;)
