### ISSUE TITLE
Mcommerce - Redirect To Other Module After Order Completion

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#314]
Often app admins want the app user taken to a specific section in the app **AFTER** the order was placed in the Mcommerce module but currently there's no way to do that.

For example: After placing an order, the app user may need to be taken to a Custom Page for special (or privileged) information; Or after an order, the app user may need to be taken to a Booking Form.

If a "Redirect to page/module"  option was added to the Mcommerce module (similar to how we currently link to other modules/pages), app admins can combine the Mcommerce module with other modules to make some really good apps.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more one year?

**Comment by SiberianCMS** [comment]
M-Commerce is due for a complete overhaul, not doing so.
