### ISSUE TITLE
Newswall Push Notification

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/Siberian#319]
It would be nice if we had better newswall features, like adding buttons/cover images/vidoes etc like custom pages - but most importantly the option to automatically send push notifications to users informing them of the a new news item.

**Comment by karargaht** [comment]
Yes, It would be so nice

**Comment by clifton11221** [comment]
I agree... These would be "very welcomed" additions.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more one year?

**Comment by Slicit** [comment]
Will be added in NewWall v2 with 4.17.0
