### ISSUE TITLE
M-Commerce ISSUE

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/Siberian#321]
There is a real issue with the ADD on feature for the M-Commerce - currently, you can only ADD one first option add with a price - for example, lets set up a product

IN this example I am using a take away on the M-Commerce - I have added a product called PIZZA.

Pizza > Product Format (additional pricing options you can set up for different formats/sizes this is excellent, for example like s/m/l) > then you have> MY PRODUCT'S OPTIONS (but you can only add 1 - maybe that extra product is an add on to the pizza like chicken/beef/jalapenos etc...there is no option to allow multiple with different pricing etc.) you can then add > MY PRODUCT'S LIST CHOICE OPTIONS (but no pricing available, this should be saved for the FREEBIE items to the pizza like sauce etc.

The MY PRODUCT OPTIONS should be available to ADD singular or multiple - with the option of the back end management setting it to singular or multiple - this is a must for a take away owner.

Anyone else had this issue / know a work around or am I missing a config????

**Comment by fouineux** [comment]
Hello,

Maybe i'm not understanding your problem, but options seems the good way to go for your case. You can add specific price to options, and your client can set a quantity to a specific option when he is ordering.

Don't hesitate to let us know if you encounter any other issue.

Regards.

**Comment by bluesnap-rock** [comment]
Hi
Yes I see options. But. Lets say this is the product.

Pizza. Product Option. Toppings> Set 5 different options like pepperoni cheese jalapenos beef chicken...all with a different price.

Within the APP 

Customer clicks pizza and wants to add 3 of those extra options....it doesnt let you. You can only choose one option from dropdown. 

Multiple choice check boxes are available for MY PRODUCT'S LIST CHOICE OPTIONS but you cant add prices to those options. That would be best.

There is also an issue with ordering..a customer can order (in this instance a takeaway app) food any time and any day. The shop owner cannot choose the days they are open.

Plus is it not poasible to allow the customer to choose the location/store branch prior to selecting products? 

Kind regards.

**Comment by fouineux** [comment]
Hi,

I see what the problem is. You have to consider each topping as a group of options, and then customer can choose every topping he wants. You can also "force" them to choose at least one topping, by the required property of each option.

![image](https://user-images.githubusercontent.com/1248082/27325610-4b245ae4-55a9-11e7-84ab-191de693c138.png)

In this example i've separated each topping, so they can appear and be choosen separately. It could be a little confusing if you have a lot of topping, but this is the most convenient way to match every case of use of the mcommerce module.

Regarding the store choice, unfortunately the module is made in the way that you have to chose it once you start validating your cart, so after selecting your products.

Same for the opening hours, the module doesn't have any way to "close" the store on app side for now.

However, this two points are good ideas to improve the MCommerce module.

**Comment by bluesnap-rock** [comment]
Hi

Yes I figured probably for now to add multiple options....but if there was a lot of options the app starts to feel silly. I think it would be best to be able to assign a price against the checkbox options as well.

The opening and closing is a very much urgent matter for me. One client wont order app because of it. Basically takeaway orders can be placed anytime of the day and any day and takeaway will be closed. Customers get charged and owner has to re-imburse. Its a nightmare. 

Really hope this can be implemented very soon

Thanks for reply.

Kind regards

**Comment by bluesnap-rock** [comment]
Is it not possible to have an in-app link point to the m-commerce - doesn't show in the list?

**Comment by bluesnap-rock** [comment]
Also the delivery radius doesnt work. If you put an incorrect postcode with no space and street as just house number or missspelt street the delivery option is available. Plus tried on multiple postcodes within 5 miles and its hit and miss. The store is set to 15 mile radius. Some post codes work some dont.

**Comment by portalidea** [comment]
I've the same problem.
If you select a pizza, for example, you can select if you want add wurstel, mushrooms, ketchup, kebab, etc. so we need checkbox not radio button.
It's not logical to have a pizza and select wurstel...and then select how many wurstel...or mushrooms and then select the quantity of mushrooms.
It's logical to have a list (checkbox) of options to select one or more of it and add price to the total.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more one year?

**Comment by Anais527** [comment]
Hello on these options in M Commerce do you know if we can block only 1 choice of options?

**Comment by SiberianCMS** [comment]
M-Commerce is due for a complete overhaul, not doing so.
