### ISSUE TITLE
WordPress Integration: Integrate User/Member Info & Login

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#377]
It would be great if the WordPress Integration module (or a new module) would integrate the WordPress user/member information (Login, Register, Avatar, etc).

Most requests that I see are to integrate the app with the website.  Not to mention that most websites run on WordPress.

I'm not sure if the WP plugin below would help but an integration of WP user accounts with Siberian apps would definitely would be a welcomed module to the Siberian community.

[https://wordpress.org/plugins/json-api-user/](url)

**Comment by davidwebs** [comment]
Yes, I look forward to this enhancement. Also adding comments capability to the wordpress feature will be a welcomed enhancement.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more one year?
