### ISSUE TITLE
Facebook page continuous loading and blinking in app

### ISSUE THREAD

**Issue by davidwebs** [Xtraball/Siberian#403]
Hi People of Siberia,

Has anyone experienced this problem? When you add a facebook page and view it from the app, it keeps blinking and loading continuously.

This is a bug. Please any help to fix this will be appreciated.

Here's a video link to see how the facebook page displays/loads continuously.
https://s.nimbus.everhelper.me/share/1065637/ibm05dxwezf07qeykkdn

Thanks

**Comment by davidwebs** [comment]
I have applied the latest release 4.12.9 and the issue still persists. here's a link to the HTML5 version of one of the apps built on my PE platform.
https://apps.mobileappforeveryone.com/59648478b85cc/

**Comment by davidwebs** [comment]
Thanks for your response. However, I have upgraded to the latest Siberian release 4.12.9 and the issue still persists. Here's a html5 link to an app built with Siberian PE with the facebook page loading and blinking continuously.
https://apps.mobileappforeveryone.com/59648478b85cc/
You can view the link on your mobile device browser.

Please let me know your feedback.

Thanks

**Comment by theeugenegroup** [comment]
Have you configured your Facebook API?

**Comment by davidwebs** [comment]
Yes I have.
I initially observed that the facebook feature displays properly on some devices and not on some others. But after a few upgrades of my platform edition, the facebook feature doesn't display properly on any device at all.

**Comment by theeugenegroup** [comment]
Have you tried using a different facebook page for testing?

**Comment by davidwebs** [comment]
Yes. I have multiple apps on my PE and all the apps that have the facebook page feature perform the same way.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more one year?
