### ISSUE TITLE
News / Fan Wall: No Indicator That You Already "Liked" The Post

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#406]
In the News and Fan Walls, there isn't an indicator that you (the app user) already "Liked" a post.  The same icon is used whether you liked a post already or not.

This causes app users to attempt to like a post that they already liked... Yes, they get the message letting them know that they already liked it but it's still a bit confusing.

If someone already liked a post, the "heart" should change colors... Maybe it could be unfilled if it wasn't liked, and filled once the app user likes the post.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more one year?

**Comment by Slicit** [comment]
Will be ready for 4.17.0 & FanWall v2

![tLMiG0PLU1](https://user-images.githubusercontent.com/4389060/59926889-924cd180-943b-11e9-8fb7-fa65891511b6.gif)
