### ISSUE TITLE
WooCommerce Module

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/Siberian#414]
This module represents a few issues, it doesn't give error notifications when new user registers if for example they are already registered with same username etc.

When ordering, you cannot choose your delivery address, this is all based on the web stored details.

Cannot see recent orders, login/logout - there are tons of WooCommerce ionic apps so I am sure this module can be updated to represent the full use of the web store, would be highly appreciated throughout I am sure??

Currently can be confusing for the shopper when visiting the module in the APP - because they are unsure what to actually do, home page shows New User, so they are already registered, they are unsure what to do next initially looking to login. When in the cart they enter email, order is instantly created, again confusing for the shopper, they need to see confirmation of the order and or change delivery details etc if necessary.

**Comment by SiberianCMS** [comment]
[Commercial module]
Support is provided only by e-mail/tickets on helpdesk.
