### ISSUE TITLE
loader won't stop after aborting facebook connection

### ISSUE THREAD

**Issue by lsmod** [Xtraball/Siberian#481]
When login with facebook a loader modal open. If user choose not to connect by hitting back, user return to app but loader is still spinning and never stop

**Comment by lsmod** [comment]
4.12.18 have fixed the issue but on some device only. It's working on :
Sony Xperia android 7; Samsung A5 Android 7

But not on Moto G4 android 7

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more one year?

**Comment by SiberianCMS** [comment]
FB has been removed*
