### ISSUE TITLE
Plugin has been removed but always in code?

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#5]
https://github.com/Xtraball/Siberian/blob/master/ionic/platforms/android/android.json#L314
        "cordova-plugin-extension": {
             "PACKAGE_NAME": "com.appsmobilecompany.base"
          },

https://github.com/Xtraball/Siberian/blob/master/ionic/platforms/android/android.json#L788
"cordova-plugin-extension": "1.5.4",

https://github.com/Xtraball/Siberian/blob/master/ionic/platforms/android/assets/www/cordova_plugins.js#L403
"cordova-plugin-extension": "1.5.4",

**Comment by userdevel** [comment]
Any news?
Already two weeks

**Comment by userdevel** [comment]
You can see here that the module has been removed : https://github.com/Xtraball/Siberian/commit/155514905b8e6cfc79a366fa11a97989a67edc2a

The question is why there are always some codes about it?

**Comment by Slicit** [comment]
this plugin was removed from platforms not needing it anymore, there is no issue.

**Comment by userdevel** [comment]
I have looked all the code!
There are a lot of codes yet for "cordova-plugin-extension"...
Not only the points said before...
It will be nice to clean the code ;)

**Comment by userdevel** [comment]
All the old code about "cordova-plugin-extension" has been removed?

**Comment by userdevel** [comment]
No reply?
