### ISSUE TITLE
Inability To Link To Major Modules

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#518]
The  in-app links feature is an awesome tool because it enables app admins to create unique app designs (ie Home Pages) with links to the app's features.  

The ability to create these unique designs is important especially when it comes to the Apple approval process. However, the ability to create an in-app link to some of the major modules is missing.  

The missing modules include: Commerce, Jobs, Chat, Quiz, Surveys, Profile, My Account, and Donations.

Please add the ability to link to these modules soon.  This is a simple, yet very important feature to have.

**Comment by clifton11221** [comment]
Below is the reply that I received from support:

> Indeed there is an issue with the social share option. It is not shown properly in the overview . However, I have tested it with a new app and the setting is working properly in app (you have to close the app, then restart it to see the changes (social sharing activated or not)

**Comment by clifton11221** [comment]
In reference to the Commerce module, please add the ability to add in-app links to "categories" within the Commerce module.  

Adding this option will allow app admins to make very nice custom Home Pages with links to specific categories like "Children's Clothes", "Adult Clothes", etc. instead of having to go to the Commerce module, and then select a category.  

This is really needed until the Commerce module gets updated with a modern UI.

**Comment by userdevel** [comment]
@LikoV2: Any news after one year?

**Comment by Slicit** [comment]
Most of the features already have in-app links, for the others it's up to whom develops the module, and requires an update.
