### ISSUE TITLE
Audio Module: Can't Add New Songs To Existing Albums

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#531]
In the Audio module, when I attempt to add a new song to an existing album (with more than one track in it), I get redirected to a weird page with all of the page formatting stripped (see screenshot below)... Even if you click "OK" or "Save" nothing happens.

When adding a totally new song to a new album everything works fine.

I'm using MAE v4.13.3.  I believe the bug started with the release of the new audio player (might be 4.13 release)

![audio_bug](https://user-images.githubusercontent.com/21089972/36320828-972466f8-1315-11e8-963e-5f3e6f0609ed.jpg)

**Comment by LikoV2** [comment]
Hi,

I can't reproduce your issue, could you please check if your server is meeting the requirements: https://doc.siberiancms.com/knowledge-base/siberian-server-requirements/

It looks like a missing php extension.

**Comment by ciadoreino** [comment]
I have the same problem.

**Comment by LikoV2** [comment]
Hi @ciadoreino,

Did you check the server requirements ? As stated above, I can't reproduce this issue, so it's not a general issue. It's linked to your server configuration.

**Comment by clifton11221** [comment]
My server have the required configuration.  It's hosted by Siberian.

**Comment by ciadoreino** [comment]
Hi,
I use a PE 4.13.4, PHP 5.6.26, JAVA 1.8.0_131, MySQL 5.5.53

**Comment by userdevel** [comment]
@LikoV2: Any news after one year?

**Comment by SiberianCMS** [comment]
As long as we will not add a Codec SDK, there will always be player issues of any kind.

Adding a Codec SDK is approx. 50MB in size increase for APK, so we are balancing it for the future player, and maybe will have to make it optional, which by the way makes the build more complex.
