### ISSUE TITLE
navbar appearing randomly on homepage

### ISSUE THREAD

**Issue by lsmod** [Xtraball/Siberian#535]
Only on real device: the navbar appear form time to time in the homepage. It's seems random.

**Comment by LikoV2** [comment]
Hi @lsmod,

Do you have any screenshot to provide please ? I don't understand what you mean by navbar. Thanks.

**Comment by lsmod** [comment]
Hello here are the screenshot!
with navbar:
![29243748_10216285615352867_1861858281182461952_n](https://user-images.githubusercontent.com/1526305/37522216-969c7b20-2923-11e8-8330-b86a1d7ba5a1.png)
without it
![29216848_10216285615432869_6201220592536911872_n](https://user-images.githubusercontent.com/1526305/37522219-9b7eca3a-2923-11e8-80cc-bf0305926b6c.png)

**Comment by lsmod** [comment]
issue occur with any layout

**Comment by LikoV2** [comment]
Confirmed, sometime (at the start of the app), the header will pop without text/buttons in it.

**Comment by userdevel** [comment]
@LikoV2: Any news after one year?
