### ISSUE TITLE
Radio Feature - Audio stopping/dropping on Anrdoid 6.0

### ISSUE THREAD

**Issue by gonzoradio** [Xtraball/Siberian#537]
audio keeps cutting out and disconnecting when using radio feature on Android 6.0.

Please help! We're in the middle of a major contest giveaway.

Works fine on anything below Android 6.0. iPhone has zero issues.

Here's a stream link if you want to try and recreate the issue:
https://playerservices.streamtheworld.com/api/livestream-redirect/CKGEFMAAC.aac
or
https://playerservices.streamtheworld.com/api/livestream-redirect/CKGEFMDROID.mp3

and here's some messages from logcat in android studio.....

03-05 09:42:23.195 1383-1678/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 227441577 , only wrote 227441507
03-05 09:42:23.415 24730-24730/com.ckgefm.app D/MediaPlayer: setSubtitleAnchor in MediaPlayer
**03-05 09:42:23.433 1383-1681/? E/MediaPlayerService: getDuration returned -2147483648**
03-05 09:42:23.435 1383-1759/? D/NuPlayerDriver: start(0xb619a500), state is 4, eos is 0
03-05 09:42:23.435 24730-24730/com.ckgefm.app D/MediaPlayer: getMetadata
03-05 09:42:23.435 1383-29409/? I/GenericSource: start
**03-05 09:42:23.461 1383-29418/? E/OMXNodeInstance: setConfig(67:google.mp3.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)**
03-05 09:42:23.461 1383-29418/? I/ACodec: codec does not support config priority (err -2147483648)
03-05 09:42:23.480 1383-29418/? I/MediaCodec: MediaCodec will operate in async mode
03-05 09:42:23.507 1383-29409/? D/NuPlayerDriver: notifyListener_l(0xb619a500), (6, 0, 0)
03-05 09:42:23.963 1383-1678/? D/AudioFlinger: mixer(0xb4340000) throttle end: throttle time(2)
03-05 09:42:24.024 1383-1677/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 227463804 , only wrote 227463320

thanks!

**Comment by userdevel** [comment]
@LikoV2: Any news after one year?

**Comment by Slicit** [comment]
4.17.0 adds new options for Android and audio/ battery optimization, etc...
