### ISSUE TITLE
NOT FIREWALL + android 7 8 OPTIMIZATION BUG Icecast streams NOT WORKING since Shoutcast fix // Radio Player

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/Siberian#538]
Just a heads up on this Bug as is not firewall ??

After checking out the new player the problem was the new player had not been updated in siberiancms

I installed a separate single system and copied the new php player and it works fine so this was an update issue and most likely others with same problem should check there one too, working copy below of new player and old one below U/S after 4.12.7.

There is also a bug in siberian cms more a missing switch to tell android 7 and 8 to bypass battery optimization otherwise unless you tell everyone to turn it off and possibly also the wifi saving the player will not keep playing after max 5 mins so we need to address this problem guys..

**Comment by rogerdavis198** [comment]
working Player

<?php

/**
 * Class Radio_Mobile_RadioController
 */
class Radio_Mobile_RadioController extends Application_Controller_Mobile_Default {

    /**
     * @param $radio
     * @return array
     */
    public function _toJson($radio){
        $json = array(
            'url' => addslashes($radio->getData('link')),
            'title' => $radio->getTitle(),
            'background' => $this->getRequest()->getBaseUrl() .
                '/images/application' . $radio->getBackground(),
        );

        return $json;
    }

    /**
     * Find action
     */
    public function findAction() {
        if ($valueId = $this->getRequest()->getParam('value_id')) {
            try {
                $radio = (new Radio_Model_Radio())
                    ->find([
                        'value_id' => $valueId
                    ]);

                // Fix for shoutcast, force stream!
                $contentType = Siberian_Request::testStream($this->getData('link'));
                if(!in_array(explode('/', $contentType)[0], ['audio']) &&
                    !in_array($contentType, ['application/ogg'])) {
                    if(strrpos($this->getData('link'), ';') === false) {
                        $this->setData('link', $this->getData('link') . '/;');
                    }
                }

                $data = [
                    'radio' => $this->_toJson($radio)
                ];
            } catch (Exception $e) {
                $data = [
                    'error' => true,
                    'message' => $e->getMessage()
                ];
            }
        } else {
            $data = [
                'error' => true,
                'message' => __('An error occurred while loading. Please try again later.')
            ];
        }

        $this->_sendJson($data);
    }

}

**Comment by rogerdavis198** [comment]
Faulty player after 4.12.8

<?php

class Radio_Mobile_RadioController extends Application_Controller_Mobile_Default {

    public function _toJson($radio){
        $json = array(
            "url" => $url = addslashes($radio->getLink()),
            'title' => $radio->getTitle()
        );

        return $json;
    }

    public function findAction() {

        if($value_id = $this->getRequest()->getParam('value_id')) {
            
            try {
                
                $radio_repository = new Radio_Model_Radio();
                $radio = $radio_repository->find(array('value_id' => $value_id));

                if(substr($radio->getLink(), -1) == "/") {
                    $stream_tag = ";";
//                    $stream_tag = ";stream.nsv&type=mp3";
                } else {
                    if(mb_stripos($radio->getLink(), "/", 8) > 0) {
                        $stream_tag = "";
//                        $stream_tag = "?stream.nsv&type=mp3";
                    } else {
//                        $stream_tag = "/;stream.nsv&type=mp3";
                        $stream_tag = "/;";
                    }
                }

                $radio->setLink($radio->getLink().$stream_tag);

                $data = array("radio" => $this->_toJson($radio));
            }
            catch(Exception $e) {
                $data = array('error' => 1, 'message' => $e->getMessage());
            }

        } else {
            $data = array('error' => 1, 'message' => $this->_("An error occurred while loading. Please try again later."));
        }

        $this->_sendHtml($data);

    }

}

**Comment by gonzoradio** [comment]
experiencing same issue on Android 6.0 devices.  tried to address it here: https://github.com/Xtraball/SiberianCMS/issues/537

radio stream dies by 5 minutes, most often less.  is there a quick fix? i have a contest on-air promoting the app.  currently redirecting with link feature to external browser.

**Comment by rogerdavis198** [comment]
you can try this, make a html entry in your app and copy below code but change the name and stream link, change the icon to a radio button, It should just use the phones html5 capabilities and will only work when that button is open , worth a try and should work ok hopefully to get you out of trouble, just add as extra player on the app.

not a fix but worth a try



<!DOCTYPE html>
<html>
<head>
<style>
body {
    background-color: #3a9fbf;
}
</style>
</head>
<body>
</body>
</html>
<h6>Press To Play! Press or Exit to Stop!</h6>
<h4 style="text-align: center;"><strong> ^ Big L 1 Studio Quality 96k OPUS ^ </strong> </h4>
<p style="text-align: center;"><audio autoplay="no" controls="controls"><audio autoplay="no" controls="controls"></audio><source src="http://stream2.dyndns.tv:8100/streamtest.opus" type="audio/ogg" /></audio> 
</h6>

**Comment by rogerdavis198** [comment]
you can add a html 5 player to get you out of trouble at the mo if you wish to try it. add a source button, copy cod attached, change station name and stream link, change icon , it should use the phones permission for its own html5 players and keep going, a little basic but it does work. on my test phones.

if you download the BigL Radio Player in the app store you can check it out on your phone first and it only plays when that button open but atleast it plays ok this end..
[html5-player-for-app.txt](https://github.com/Xtraball/SiberianCMS/files/1784947/html5-player-for-app.txt)

**Comment by gonzoradio** [comment]
Thanks so much for taking the time to reply and provide a solution! I'll set it up and see what my PD prefers. Fingers crossed for a quick resolution from Siberian crew.  ;8P

**Comment by LikoV2** [comment]
Hi @gonzoradio,

We tested some Icecast streams, and it's working fine on the latest version of Siberian (4.13.6). The only issue we could find was the firewall that blocked some ports used by Icecast.

**Comment by gonzoradio** [comment]
we don't use ice cast streams. We have 6 fully licensed stations on Triton Digital (formerly stream the world).  I have also tested mp3 mounts from other broadcasters using other professional streaming companies and they stay connected for a little longer but are dropped also.  errors in android studio are non existent in version 5.1 or lower and present on all 6.0 and higher.  The media player used in siberian has been troubled for years, the latest upgrades to the player have made things much worse.  We'll continue to look for a solution and hope siberian will too. thanks!

**Comment by clifton11221** [comment]
Please provide a sample url stream so maybe the dev team can test against your stream.

**Comment by gonzoradio** [comment]
Sample url's located here. Thanks!

https://github.com/Xtraball/SiberianCMS/issues/537

**Comment by rogerdavis198** [comment]
Hi here is a few to play with

stream2.dyndns.tv:8100

Icecast server with loads of formats

And shoutcast try these

stream1.dyndns.tv:9150

stream1.dyndns.tv:9160

Cheers Guys

⁣Sent from BlueMail ​

**Comment by userdevel** [comment]
@LikoV2: Any news after one year?

**Comment by rogerdavis198** [comment]
Hi guys any chance we can have a pop up for Android to either link it to the optimisation in settings like other apps do with this problem or a one time pop-up explaining how to turn the optimization off on the setting for the audio player apps.

Thanks
