### ISSUE TITLE
Remove ADMOB with In App Purchase

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/Siberian#543]
Is this possible?

**Comment by clifton11221** [comment]
Not at this time (that I'm aware of).

**Comment by davidwebs** [comment]
This will be a great enhancement, so that app users can remove adverts with in app purchase.

**Comment by userdevel** [comment]
+1 for purchase app

And possibility to have monthly (6/12/24months) subscription option...

**Comment by userdevel** [comment]
@LikoV2: Any news after one year?

**Comment by SiberianCMS** [comment]
InAppPurchase native code have been added, team is working on support modules.
