### ISSUE TITLE
Enable/Disable Startup Image in "Application" tab of app editor

### ISSUE THREAD

**Issue by davidwebs** [Xtraball/Siberian#557]
There should be an option to enable/disable the startup image in the "Application" tab of the app editor, so that once an app is launched on the mobile phone, it will just open without the startup image with loading...

**Comment by LikoV2** [comment]
Hi @davidwebs,

Why would you want no startup image on startup ?

**Comment by davidwebs** [comment]
Some layouts come with their own home page/startup slider, hence for those layouts some people would not want another startup image, then home page slider before app displays.
Also, startup image is not the main content of the app, and can slow down the main content loading sometimes. So it is better for the app owner/builder to have an option to enable or disable this feature. In my opinion it should be optional rather than force all apps to have a startup image.

**Comment by davidwebs** [comment]
@LikoV2 
First off startup image isn't mandatory, there's no rule that makes it so. Secondly, even though facebook app has one doesn't mean all apps on the app store have.
Thirdly, take a look at facebook startup again and most other apps' startup, its an interactive startup slider not a static startup image.

You also need to understand my point; I'm not saying eliminate startup image, I'm saying make it optional. Or even better, make it interactive, like some apps which have a series of interactive startup  slides that gives the user information about the app, then user clicks NEXT, NEXT, NEXT until the app displays. And most apps that do that, only display this interactive startup when the app is launched for the first time on the device.
Siberian startup image on the other hand displays every time the app starts up and it's just static. (can be frustrating sometimes). 

**Suggestion:** There should be a startup builder to allow an interactive startup slider or a static image depending on the app builder's choice, and there should be an option to enable or disable it.

**Comment by LikoV2** [comment]
@davidwebs,

Siberian is an app generator tool, there are restrictions that come with it, you have to understand that we cannot generate highly customized apps with a generator.

We heard your suggestion, however, it's not on our to-do list right now. As Siberian Single-App Edition is open-source, you can also contribute to it, by submitting a pull request.

**Comment by davidwebs** [comment]
@LikoV2 
Ok. 
Though my suggestion was for the Siberian Platform Edition.
