### ISSUE TITLE
Newswall date/time options

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#561]
It is possible to add options for time/date:
- Publish "now"
- ~~Choice the date AND the time because time is missing : "00:00"~~ since 4.13.19
- seconds
- AM/PM time or 24H time
- time with time zone
- show or hide the time
- add a color for selected date in more today (blue for example)

Note: Some time options can be in other modules.

**Comment by userdevel** [comment]
Thanks for adding the time section in menu!

I added the seconds part and a color for selected date (in blue for example) in more today: yellow/orange

**Comment by userdevel** [comment]
@SiberianCMS @dbyzero @Slicit @LikoV2: Any news for tickets?
#578
#576
#570
#569
#568
#567
#566
#565
#564
#563
#562
#561
#560
#559
#558

**Comment by userdevel** [comment]
@SiberianCMS @alexyves @dbyzero @Slicit @LikoV2: Any news for tickets?
Because there are problems of date, time, etc
#578
#576
#570
#569
#568
#567
#566
#565
#564
#563
#562
#561
#560
#559
#558

**Comment by userdevel** [comment]
@SiberianCMS @alexyves @dbyzero @Slicit @LikoV2: Any news for date/time problems?
- https://github.com/Xtraball/SiberianCMS/issues/created_by/userdevel

**Comment by userdevel** [comment]
@LikoV2: Any news after one year?

**Comment by Slicit** [comment]
Theses options will be fixed/improved in 4.17.0 in Social Wall module.

NewsWall & FanWall will be deprecated.
