### ISSUE TITLE
Fan Wall date/time options

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#566]
It is possible to add options for time/date:
- Publish "now"
- ~~Choice the date AND the time because time is missing : "00:00"~~ since 4.13.19
- seconds
- AM/PM time or 24H time
- time with time zone
- show or hide the time
- add a color for selected date in more today (blue for example)

Note: Some time options can be in other modules.

**Comment by userdevel** [comment]
Thanks for adding the time section in menu!

I added the seconds part and a color for selected date (in blue for example) in more today: yellow/orange

**Comment by userdevel** [comment]
@LikoV2: Any news after one year?

**Comment by Slicit** [comment]
No news, will see after 4.17.0 & FanWall v2 too.

**Comment by Slicit** [comment]
Theses options will be fixed/improved in 4.17.0 in Social Wall module.

NewsWall & FanWall will be deprecated.
