### ISSUE TITLE
Roadmap is down?

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#576]
Hello all,

The roadmap is down?

"The board is actually under maintenance, please check again later, thanks."

**Comment by clifton11221** [comment]
Yes... A new site is being created.

**Comment by userdevel** [comment]
No official reply?

**Comment by userdevel** [comment]
There is a temporary roadmap here: https://www.siberiancms.com/community/d/745-roadmap-4-15-4-16

**Comment by Slicit** [comment]
@userdevel  this is now the official roadmap.
https://www.siberiancms.com/community/d/745-roadmap-4-16-4-17

Anyway, we're done migrating & push back references, we've merged older SiberianCMS with Siberian, SiberianCMS now correctly redirects to HERE https://github.com/Xtraball/Siberian

While all issues are preserved.

You can re-open what's relevant.

**Comment by userdevel** [comment]
You can now import few new issues from https://github.com/Xtraball/Siberian416/ here?

**Comment by userdevel** [comment]
Badly, we (not admin) have not possibility to re-open issues, there are a lot...
Easy to move some few issues here?

**Comment by Slicit** [comment]
Done!

**Comment by userdevel** [comment]
Thanks for your changes, it is really better for all now.
It is not possible to have only one link/redirection for the roadmap?
Example: https://www.siberiancms.com/roadmap ?

**Comment by userdevel** [comment]
You have forgotten to move this opened PR: https://github.com/Xtraball/Siberian416/pull/21
It is not impossible to move merged/closed PR too?
