### ISSUE TITLE
PHP 7.1, 7.2, 7.3 not supported -> problems

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#593]
There are problems with PHP 7.1, 7.2, 7.3.

Can you resolve it?

http://www.php.net/ChangeLog-7.php#7.1.0 since 01 Dec 2016
http://www.php.net/ChangeLog-7.php#7.2.0 since 30 Nov 2017
7.3.x in progress : http://php.net/

**Comment by LikoV2** [comment]
Hi,

It's not scheduled, no. PHP7.1+ is not supported.

**Comment by userdevel** [comment]
https://secure.php.net/supported-versions.php
Warning for security!
Please upgrade the code.

New OS have new PHP version included!

**Comment by ranjbar2446** [comment]
have the same problem.

**Comment by userdevel** [comment]
Linked to:
- https://github.com/Xtraball/SiberianCMS/issues/593
- https://github.com/Xtraball/Siberian/issues/15

**Comment by Slicit** [comment]
We actually support up to PHP 7.2

And have partial support for PHP 7.3, it's in progress, PHP 7.3 being more strict than 7.2 we have lot of code to review and fix before officially supporting it.

**Comment by userdevel** [comment]
PHP 7.2 is really full supported for the moment?

**Comment by userdevel** [comment]
Excellent, soon 7.3?

**Comment by Slicit** [comment]
7.3 already in progress, but as said, it will require way more work, 7.3 is way more strict than 7.2 and lot of code which was "tolerated" up to PHP 7.2 is not anymore, so there is lot of things to check & test, and this will also maybe breaks lot of external modules, etc ...
