### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by applimoby** [Xtraball/Siberian#6]
In the RSS module, youtube videos of the RSS feed is not displayed . it works perfectly with version 3.17. There is a solution to restore the display of YT videos in the RSS feed ?

**Comment by clifton11221** [comment]
I agree that YouTube videos should should be displayed in the RSS feed.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more three years?

**Comment by Slicit** [comment]
RSS was completely rebuilt in 4.16.x so it's not relevant anymore, and yet, if an iframe is embed with a youtube video, it will be displayed in the rss feed.
