### ISSUE TITLE
Error during installation process when installing to Azure

### ISSUE THREAD

**Issue by GeorgeJarreHamilton** [Xtraball/Siberian#602]
Hi Everybody,

Help with installation would be appreciated. Already succeeded installing to Godaddy servers but now when trying to install to Azure (as web app) I constantly receive error while entering database information during installation process. Error is caused by mixed content (visible in screenshot). My Azure setup runs on Apache and PHP 7.0.32.

I have read basically every info what I was able to find and only relevant hint was to install from http.
Does anyone have experience from installing Siberian CMS to Azure?

Are you able to help with this?
Thanks!

![screen shot 2018-11-12 at 23 57 55](https://user-images.githubusercontent.com/17648954/48378445-484b8280-e6d9-11e8-8f75-646f745dc8fc.png)

**Comment by p-andreas** [comment]
I think this is a duplicate of:  https://github.com/Xtraball/SiberianCMS/issues/253

**Comment by SiberianCMS** [comment]
@GeorgeJarreHamilton you are installing from HTTPS and Installer requires an HTTP endpoint, which if not available will lead to an error.

Solution: allows both HTTP/HTTPS while installing at least.

Note: un-burried topic, if still relevant, create a new ticket, thanks.

**Comment by Neustradamus** [comment]
@SiberianCMS: Can you update the installer with a full HTTPS support?

We must not transmit important data without encryption (passwords, etc.).

/!\ There is a security problem here.
