### ISSUE TITLE
Error 500 while opening Editor for the first time

### ISSUE THREAD

**Issue by neodavids** [Xtraball/Siberian#607]
I m trying to My siberian application but it is  stuck at creating app name and it doesn't move to done! I ignored it and refreshed and I'm  having a fatal error :
(
    [storage:ArrayObject:private] => Array
        (
            [exception] => Zend_Db_Statement_Exception Object
                (
                    [_previous:Zend_Exception:private] => 
                    [message:protected] => SQLSTATE[HY093]: Invalid parameter number: no parameters were bound
                    [string:Exception:private] => 
                    [code:protected] => 0
                    [file:protected] => /home/nuelogic/public_html/drupe/lib/Zend/Db/Statement/Pdo.php
                    [line:protected] => 234
                    [trace:Exception:private] => Array
                        (
                            [0] => Array
                                (
                                    [file] => /home/nuelogic/public_html/drupe/lib/Zend/Db/Statement.php
                                    [line] => 303
                                    [function] => _execute
                                    [class] => Zend_Db_Statement_Pdo
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => Array
                                                (
                                                )

                                        )

                                )

                            [1] => Array
                                (
                                    [file] => /home/nuelogic/public_html/drupe/lib/Zend/Db/Adapter/Abstract.php
                                    [line] => 480
                                    [function] => execute
                                    [class] => Zend_Db_Statement
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => Array
                                                (
                                                )

                                        )

                                )

                            [2] => Array
                                (
                                    [file] => /home/nuelogic/public_html/drupe/lib/Zend/Db/Adapter/Pdo/Abstract.php
                                    [line] => 238
                                    [function] => query
                                    [class] => Zend_Db_Adapter_Abstract
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => Zend_Db_Table_Select Object
                                                (
                                                    [

It's very long... This are just the first few lines.. any help? 
I'm using SAE - v4.15.5
 My URL/back office works fine but the main URL is showing the error

**Comment by userdevel** [comment]
Any news on it?

**Comment by nikhilborwankar** [comment]
I'm struggling with exactly the same error. Any assistance would be greatly appreciated. Thanks in advance.

**Comment by gr46** [comment]
Exactly the same problem for me as well.
