### ISSUE TITLE
Shop error

### ISSUE THREAD

**Issue by xcardonalacetania** [Xtraball/Siberian#609]
When I'm trying to add a new shop, the editor is not showed.

There is an error with locales: "No region found within the locale 'ca'"

The Response is:

Error log: error__5c8eb94da57df.log

Stack Trace:

Fatal Error: 
ArrayObject Object
(
    [storage:ArrayObject:private] => Array
        (
            [exception] => Zend_Currency_Exception Object
                (
                    [_previous:Zend_Exception:private] => 
                    [message:protected] => No region found within the locale 'ca'
                    [string:Exception:private] => 
                    [code:protected] => 0
                    [file:protected] => /var/www/html/lib/Zend/Currency.php
                    [line:protected] => 561
                    [trace:Exception:private] => Array
                        (
                            [0] => Array
                                (
                                    [file] => /var/www/html/lib/Zend/Currency.php
                                    [line] => 106
                                    [function] => setLocale
                                    [class] => Zend_Currency
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => ca
                                        )

                                )

                            [1] => Array
                                (
                                    [file] => /var/www/html/app/sae/modules/Mcommerce/Model/Payment/Method/Abstract.php
                                    [line] => 47
                                    [function] => __construct
                                    [class] => Zend_Currency
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => 
                                            [1] => 
                                        )

                                )

                            [2] => Array
                                (
                                    [file] => /var/www/html/app/sae/modules/Mcommerce/Model/Payment/Method/Paypal.php
                                    [line] => 113
                                    [function] => currencyShortName
                                    [class] => Mcommerce_Model_Payment_Method_Abstract
                                    [type] => ->
                                    [args] => Array
                                        (
                                        )

                                )

                            [3] => Array
                                (
                                    [file] => /var/www/html/app/sae/modules/Mcommerce/Model/Payment/Method.php
                                    [line] => 123
                                    [function] => currencySupportApp
                                    [class] => Mcommerce_Model_Payment_Method_Paypal
                                    [type] => ->
                                    [args] => Array
                                        (
                                        )

                                )

                            [4] => Array
                                (
                                    [file] => /var/www/html/app/sae/modules/Mcommerce/resources/design/desktop/flat/template/mcommerce/application/edit/store/edit.phtml
                                    [line] => 287
                                    [function] => currencySupportApp
                                    [class] => Mcommerce_Model_Payment_Method
                                    [type] => ->
                                    [args] => Array
                                        (
                                        )

                                )

                            [5] => Array
                                (
                                    [file] => /var/www/html/lib/Zend/View.php
                                    [line] => 108
                                    [args] => Array
                                        (
                                            [0] => /var/www/html/app/sae/modules/Mcommerce/resources/design/desktop/flat/template/mcommerce/application/edit/store/edit.phtml
                                        )

                                    [function] => include
                                )

                            [6] => Array
                                (
                                    [file] => /var/www/html/lib/Zend/View/Abstract.php
                                    [line] => 888
                                    [function] => _run
                                    [class] => Zend_View
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => /var/www/html/app/sae/modules/Mcommerce/resources/design/desktop/flat/template/mcommerce/application/edit/store/edit.phtml
                                        )

                                )

                            [7] => Array
                                (
                                    [file] => /var/www/html/lib/Siberian/View.php
                                    [line] => 220
                                    [function] => render
                                    [class] => Zend_View_Abstract
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => 
                                        )

                                )

                            [8] => Array
                                (
                                    [file] => /var/www/html/app/sae/modules/Mcommerce/controllers/Application/StoreController.php
                                    [line] => 23
                                    [function] => toHtml
                                    [class] => Siberian\View
                                    [type] => ->
                                    [args] => Array
                                        (
                                        )

                                )

                            [9] => Array
                                (
                                    [file] => /var/www/html/lib/Zend/Controller/Action.php
                                    [line] => 516
                                    [function] => editAction
                                    [class] => Mcommerce_Application_StoreController
                                    [type] => ->
                                    [args] => Array
                                        (
                                        )

                                )

                            [10] => Array
                                (
                                    [file] => /var/www/html/lib/Zend/Controller/Dispatcher/Standard.php
                                    [line] => 308
                                    [function] => dispatch
                                    [class] => Zend_Controller_Action
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => editAction
                                        )

                                )

                            [11] => Array
                                (
                                    [file] => /var/www/html/lib/Zend/Controller/Front.php
                                    [line] => 954
                                    [function] => dispatch
                                    [class] => Zend_Controller_Dispatcher_Standard
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => Siberian_Controller_Request_Http Object
                                                (
                                                    [_is_backoffice:protected] => 
                                                    [_is_application:protected] => 
                                                    [_language_code:protected] => 
                                                    [_force_language_code:protected] => 
                                                    [_is_native:protected] => 
                                                    [_use_application_key:protected] => 
                                                    [_white_label_editor:protected] => Core\Model\Base Object
                                                        (
                                                            [cache] => 
                                                            [_db_table:protected] => 
                                                            [_is_cacheable:protected] => 
                                                            [_action_view:protected] => find
                                                            [_data:protected] => Array
                                                                (
                                                                    [is_active] => 
                                                                )

                                                            [_orig_data:protected] => Array
                                                                (
                                                                )

                                                            [_specific_import_data:protected] => Array
                                                                (
                                                                )

                                                            [_mandatory_columns:protected] => Array
                                                                (
                                                                )

                                                            [_default_application_image_path] => images/application
                                                            [logger] => Siberian\Log Object
                                                                (
                                                                    [_filename:protected] => 
                                                                    [_priorities:protected] => Array
                                                                        (
                                                                            [0] => EMERG
                                                                            [1] => ALERT
                                                                            [2] => CRIT
                                                                            [3] => ERR
                                                                            [4] => WARN
                                                                            [5] => NOTICE
                                                                            [6] => INFO
                                                                            [7] => DEBUG
                                                                        )

                                                                    [_writers:protected] => Array
                                                                        (
                                                                            [0] => Zend_Log_Writer_Stream Object
                                                                                (
                                                                                    [_stream:protected] => Resource id #6
                                                                                    [_filters:protected] => Array
                                                                                        (
                                                                                        )

                                                                                    [_formatter:protected] => Zend_Log_Formatter_Simple Object
                                                                                        (
                                                                                            [_format:protected] => %timestamp% %priorityName% (%priority%): %message%

                                                                                        )

                                                                                )

                                                                        )

                                                                    [_filters:protected] => Array
                                                                        (
                                                                        )

                                                                    [_extras:protected] => Array
                                                                        (
                                                                        )

                                                                    [_defaultWriterNamespace:protected] => Zend_Log_Writer
                                                                    [_defaultFilterNamespace:protected] => Zend_Log_Filter
                                                                    [_defaultFormatterNamespace:protected] => Zend_Log_Formatter
                                                                    [_origErrorHandler:protected] => 
                                                                    [_registeredErrorHandler:protected] => 
                                                                    [_errorHandlerMap:protected] => 
                                                                    [_timestampFormat:protected] => c
                                                                )

                                                        )

                                                    [_application] => 
                                                    [_application_key:protected] => 
                                                    [_ionic_path:protected] => 
                                                    [_is_installing:protected] => 
                                                    [_mediaUrl:protected] => 
                                                    [isAllowed] => 
                                                    [_paramSources:protected] => Array
                                                        (
                                                            [0] => _GET
                                                            [1] => _POST
                                                        )

                                                    [_requestUri:protected] => /mcommerce/application_store/edit
                                                    [_baseUrl:protected] => http://localhost
                                                    [_basePath:protected] => 
                                                    [_pathInfo:protected] => /mcommerce/application_store/edit
                                                    [_params:protected] => Array
                                                        (
                                                            [module] => mcommerce
                                                            [controller] => application_store
                                                            [action] => edit
                                                            [error_handler] => ArrayObject Object
 *RECURSION*
                                                        )

                                                    [_rawBody:protected] => option_value_id=19
                                                    [_aliases:protected] => Array
                                                        (
                                                        )

                                                    [_dispatched:protected] => 1
                                                    [_module:protected] => Front
                                                    [_moduleKey:protected] => module
                                                    [_controller:protected] => error
                                                    [_controllerKey:protected] => controller
                                                    [_action:protected] => exception
                                                    [_actionKey:protected] => action
                                                )

                                            [1] => Zend_Controller_Response_Http Object
                                                (
                                                    [_body:protected] => Array
                                                        (
                                                            [default] => 
                                                        )

                                                    [_exceptions:protected] => Array
                                                        (
                                                            [0] => Zend_Currency_Exception Object
 *RECURSION*
                                                        )

                                                    [_headers:protected] => Array
                                                        (
                                                        )

                                                    [_headersRaw:protected] => Array
                                                        (
                                                        )

                                                    [_httpResponseCode:protected] => 500
                                                    [_isRedirect:protected] => 
                                                    [_renderExceptions:protected] => 
                                                    [headersSentThrowsException] => 1
                                                )

                                        )

                                )

                            [12] => Array
                                (
                                    [file] => /var/www/html/app/Bootstrap.php
                                    [line] => 474
                                    [function] => dispatch
                                    [class] => Zend_Controller_Front
                                    [type] => ->
                                    [args] => Array
                                        (
                                            [0] => Siberian_Controller_Request_Http Object
                                                (
                                                    [_is_backoffice:protected] => 
                                                    [_is_application:protected] => 
                                                    [_language_code:protected] => 
                                                    [_force_language_code:protected] => 
                                                    [_is_native:protected] => 
                                                    [_use_application_key:protected] => 
                                                    [_white_label_editor:protected] => Core\Model\Base Object
                                                        (
                                                            [cache] => 
                                                            [_db_table:protected] => 
                                                            [_is_cacheable:protected] => 
                                                            [_action_view:protected] => find
                                                            [_data:protected] => Array
                                                                (
                                                                    [is_active] => 
                                                                )

                                                            [_orig_data:protected] => Array
                                                                (
                                                                )

                                                            [_specific_import_data:protected] => Array
                                                                (
                                                                )

                                                            [_mandatory_columns:protected] => Array
                                                                (
                                                                )

                                                            [_default_application_image_path] => images/application
                                                            [logger] => Siberian\Log Object
                                                                (
                                                                    [_filename:protected] => 
                                                                    [_priorities:protected] => Array
                                                                        (
                                                                            [0] => EMERG
                                                                            [1] => ALERT
                                                                            [2] => CRIT
                                                                            [3] => ERR
                                                                            [4] => WARN
                                                                            [5] => NOTICE
                                                                            [6] => INFO
                                                                            [7] => DEBUG
                                                                        )

                                                                    [_writers:protected] => Array
                                                                        (
                                                                            [0] => Zend_Log_Writer_Stream Object
                                                                                (
                                                                                    [_stream:protected] => Resource id #6
                                                                                    [_filters:protected] => Array
                                                                                        (
                                                                                        )

                                                                                    [_formatter:protected] => Zend_Log_Formatter_Simple Object
                                                                                        (
                                                                                            [_format:protected] => %timestamp% %priorityName% (%priority%): %message%

                                                                                        )

                                                                                )

                                                                        )

                                                                    [_filters:protected] => Array
                                                                        (
                                                                        )

                                                                    [_extras:protected] => Array
                                                                        (
                                                                        )

                                                                    [_defaultWriterNamespace:protected] => Zend_Log_Writer
                                                                    [_defaultFilterNamespace:protected] => Zend_Log_Filter
                                                                    [_defaultFormatterNamespace:protected] => Zend_Log_Formatter
                                                                    [_origErrorHandler:protected] => 
                                                                    [_registeredErrorHandler:protected] => 
                                                                    [_errorHandlerMap:protected] => 
                                                                    [_timestampFormat:protected] => c
                                                                )

                                                        )

                                                    [_application] => 
                                                    [_application_key:protected] => 
                                                    [_ionic_path:protected] => 
                                                    [_is_installing:protected] => 
                                                    [_mediaUrl:protected] => 
                                                    [isAllowed] => 
                                                    [_paramSources:protected] => Array
                                                        (
                                                            [0] => _GET
                                                            [1] => _POST
                                                        )

                                                    [_requestUri:protected] => /mcommerce/application_store/edit
                                                    [_baseUrl:protected] => http://localhost
                                                    [_basePath:protected] => 
                                                    [_pathInfo:protected] => /mcommerce/application_store/edit
                                                    [_params:protected] => Array
                                                        (
                                                            [module] => mcommerce
                                                            [controller] => application_store
                                                            [action] => edit
                                                            [error_handler] => ArrayObject Object
 *RECURSION*
                                                        )

                                                    [_rawBody:protected] => option_value_id=19
                                                    [_aliases:protected] => Array
                                                        (
                                                        )

                                                    [_dispatched:protected] => 1
                                                    [_module:protected] => Front
                                                    [_moduleKey:protected] => module
                                                    [_controller:protected] => error
                                                    [_controllerKey:protected] => controller
                                                    [_action:protected] => exception
                                                    [_actionKey:protected] => action
                                                )

                                        )

                                )

                            [13] => Array
                                (
                                    [file] => /var/www/html/lib/Zend/Application.php
                                    [line] => 366
                                    [function] => run
                                    [class] => Bootstrap
                                    [type] => ->
                                    [args] => Array
                                        (
                                        )

                                )

                            [14] => Array
                                (
                                    [file] => /var/www/html/index.php
                                    [line] => 113
                                    [function] => run
                                    [class] => Zend_Application
                                    [type] => ->
                                    [args] => Array
                                        (
                                        )

                                )

                        )

                    [previous:Exception:private] => 
                )

            [type] => EXCEPTION_OTHER
            [request] => Siberian_Controller_Request_Http Object
                (
                    [_is_backoffice:protected] => 
                    [_is_application:protected] => 
                    [_language_code:protected] => 
                    [_force_language_code:protected] => 
                    [_is_native:protected] => 
                    [_use_application_key:protected] => 
                    [_white_label_editor:protected] => Core\Model\Base Object
                        (
                            [cache] => 
                            [_db_table:protected] => 
                            [_is_cacheable:protected] => 
                            [_action_view:protected] => find
                            [_data:protected] => Array
                                (
                                    [is_active] => 
                                )

                            [_orig_data:protected] => Array
                                (
                                )

                            [_specific_import_data:protected] => Array
                                (
                                )

                            [_mandatory_columns:protected] => Array
                                (
                                )

                            [_default_application_image_path] => images/application
                            [logger] => Siberian\Log Object
                                (
                                    [_filename:protected] => 
                                    [_priorities:protected] => Array
                                        (
                                            [0] => EMERG
                                            [1] => ALERT
                                            [2] => CRIT
                                            [3] => ERR
                                            [4] => WARN
                                            [5] => NOTICE
                                            [6] => INFO
                                            [7] => DEBUG
                                        )

                                    [_writers:protected] => Array
                                        (
                                            [0] => Zend_Log_Writer_Stream Object
                                                (
                                                    [_stream:protected] => Resource id #6
                                                    [_filters:protected] => Array
                                                        (
                                                        )

                                                    [_formatter:protected] => Zend_Log_Formatter_Simple Object
                                                        (
                                                            [_format:protected] => %timestamp% %priorityName% (%priority%): %message%

                                                        )

                                                )

                                        )

                                    [_filters:protected] => Array
                                        (
                                        )

                                    [_extras:protected] => Array
                                        (
                                        )

                                    [_defaultWriterNamespace:protected] => Zend_Log_Writer
                                    [_defaultFilterNamespace:protected] => Zend_Log_Filter
                                    [_defaultFormatterNamespace:protected] => Zend_Log_Formatter
                                    [_origErrorHandler:protected] => 
                                    [_registeredErrorHandler:protected] => 
                                    [_errorHandlerMap:protected] => 
                                    [_timestampFormat:protected] => c
                                )

                        )

                    [_application] => 
                    [_application_key:protected] => 
                    [_ionic_path:protected] => 
                    [_is_installing:protected] => 
                    [_mediaUrl:protected] => 
                    [isAllowed] => 
                    [_paramSources:protected] => Array
                        (
                            [0] => _GET
                            [1] => _POST
                        )

                    [_requestUri:protected] => /mcommerce/application_store/edit
                    [_baseUrl:protected] => http://localhost
                    [_basePath:protected] => 
                    [_pathInfo:protected] => /mcommerce/application_store/edit
                    [_params:protected] => Array
                        (
                            [module] => mcommerce
                            [controller] => application_store
                            [action] => edit
                        )

                    [_rawBody:protected] => option_value_id=19
                    [_aliases:protected] => Array
                        (
                        )

                    [_dispatched:protected] => 1
                    [_module:protected] => mcommerce
                    [_moduleKey:protected] => module
                    [_controller:protected] => application_store
                    [_controllerKey:protected] => controller
                    [_action:protected] => edit
                    [_actionKey:protected] => action
                )

        )

)

**Comment by userdevel** [comment]
Any news on it?

**Comment by Slicit** [comment]
Can you test again with the latest version and let me know? thanks
@xcardonalacetania

**Comment by SiberianCMS** [comment]
Just change your App locale/language (Editor > Design)
`ca` is not valid, it should be something like `ca_CA`
