### ISSUE TITLE
JOB MODULE ERRORS

### ISSUE THREAD

**Issue by yuqwadich** [Xtraball/Siberian#610]
In the module jobs ( Single App Version) there are two issues

1. When the module starts with 20/30 and more ads, the ads are not displayed, sometimes the list is empty ( with ads located near the position)

2. When a user reload the app the ads are repeated a lot of time.

( i can attach a sample from a working app)

**Comment by userdevel** [comment]
Any news on it?

**Comment by Slicit** [comment]
A complete job refactoring has been done for the 4.16.11, should bed released soon.

**Comment by Slicit** [comment]
Complete Job update released.
