### ISSUE TITLE
APKs not work in the background

### ISSUE THREAD

**Issue by JotaHuaixan** [Xtraball/Siberian#611]
Hi,

I bought the Siberian CMS for professional work. I'm a web-radio builder. For me the acquisition was futile, money thrown out. I will not be able to work like the Siberian CMS. It is Siberian's duty to correct such mistakes as the service is sold. The buyer is financially disadvantaged.
APKs generated by Siberian do not work in the background. On the RADIO item the stream stops as soon as Android goes into sleep. PUSH is also not received while the APK is not opened.
It does not appear to be a problem in the stream, but in the compilation or source of the APK.

- José Huaixan.

**Comment by userdevel** [comment]
Any news on it?
