### ISSUE TITLE
Booking date/time menu is missing

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#614]
It is possible to add the "menu" for date and time like "Beginning date" in Calendar module?

- Imported from the old place.

**Comment by Slicit** [comment]
Example with picture? I really don't understand what you're asking for!

**Comment by userdevel** [comment]
My original ticket : https://github.com/Xtraball/Siberian/issues/562

**Comment by userdevel** [comment]
Actualy in the Booking module, I forgot that I have seen here before...
- Design : List / Card
- Date format : YYYY-MM-DD HH:mm etc.

But in application:

Booking

Information
First name / Last name
Phone
Email
Number of people <-- Warning limited to 20
Location
Date & time

Booking details
Booking details

Comment
Comment

Example, in other languages than English, it is translated?
Directly good on mobile users? If Italians, ...

Only one date/time for booking, and no ending date/time?

It is not possible to see a booking list? And in a calendar?

**Comment by Slicit** [comment]
Already addressed, you can have either `Date & time` or `Check in & check out`

**Comment by userdevel** [comment]
I do not see "Check in & check out"
