### ISSUE TITLE
Newswall date/time options

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#615]
It is possible to add options for time/date:
- Publish "now"
- ~~Choice the date AND the time because time is missing : "00:00"~~ since 4.13.19
- seconds
- AM/PM time or 24H time
- time with time zone
- show or hide the time
- add a color for selected date in more today (blue for example)

Note: Some time options can be in other modules.

- Imported from the old place.

**Comment by userdevel** [comment]
My original ticket : https://github.com/Xtraball/Siberian/issues/561

**Comment by Slicit** [comment]
Closing.

Some fixed, some not relevant anymore.

![Screen Shot 2019-06-27 at 18 24 17](https://user-images.githubusercontent.com/4389060/60283161-d42cba80-9908-11e9-9a66-aa84bf5e850b.png)

Please check Social Wall when 4.17.0 gets released.
