### ISSUE TITLE
branches point

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#621]
Old branches have been imported? Need to keep?
- feature/webnavlink_bis
- hotfix/TG-368
- changelog-test

In the other repository, there were a lot of branches too ^^

**Comment by Slicit** [comment]
Only tags really matters, branches it's ok.

**Comment by userdevel** [comment]
But she can be removed no? Interest to keep? ^^

**Comment by Slicit** [comment]
only master/developer have interest

**Comment by userdevel** [comment]
So you can delete old branches :)
