### ISSUE TITLE
Currency (money) must be possible with "," and "."

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#623]
Note in Catalog module: I see that the currency is not showed (not like in Set Meal)

For all modules, in the World, currency can be write with "." and ",".

In Catalog module, add a new product:
- Price: We can enter 10,00 or 10.00
- Price: We can enter 9,90 but it is saved 9,00 (Same for Set Meal)
- Price: We can enter 10.50: it is good
- For format part: We can not enter 10.00 but only 10,00

In Commerce module, add a new product:
- Price: We can enter 100.00: it is good
- Price: We can enter 100.50: it is good
- Price: we can not enter 100,00: "Please enter a valid number."
- For format part: We can not enter 10,00: "Please enter a valid number."
- For format part: We can enter 10.00: it is good

Can you solve this problem?
This problem is maybe in other modules too?

**Comment by userdevel** [comment]
@Slicit: Have you seen?

**Comment by userdevel** [comment]
@Slicit: Have you progressed about these bugs?

**Comment by userdevel2** [comment]
This bug has been solved?
What is the version?
I see a lot of closed tickets.
