### ISSUE TITLE
Contact module address problem, move sections, impossible to add links

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#624]
In Contact module, if there is not Google Maps  API Key (no problem):
"You must set a Google Maps API Key in Settings > API in order to use this feature."

But the address is not showed, there are two parts:
- Between Name and Description
- Locate, if API, it normaly works in preview? If not API, disable in application?

Locate : Add an option to disable, Google Maps API Key is not needed.

Good, I see:
> Overview
> This feature is disabled in this preview

For:
- Email
- Website
- Facebook
- Twitter

But not for:
- Phone
Option to show or hide Locate ?

It is not possible to move section...

Impossible to add many other links...

In application:

Contact

Name
Invisible Address?
Description

Phone
Locate
Email
Website
Facebook
Twitter

PS : I tried to change "Address" section that I have enter a long time ago, I can not, I have this message: "We are unable to validate your address!", why?

Please note that this actual "Address" is not showed in application...

**Comment by Slicit** [comment]
For what concerned about "Move Sections" If you want an advanced contact page, create it With a CMS/Custom Page, you can do the same with moveable sections.

For the Google API, it's to validate the address and get coordinates.

**Comment by userdevel** [comment]
How it is possible to change the address?

> I tried to change "Address" section that I have enter a long time ago, I can not, I have this message: "We are unable to validate your address!", why?
> 
> Please note that this actual "Address" is not showed in application...

**Comment by userdevel** [comment]
The big problem in this module is "We are unable to validate your address!"

**Comment by Slicit** [comment]
This is scheduled for 4.17.1.
