### ISSUE TITLE
Fan Wall : Google Maps API Key : Add an option to disable "Near me settings"

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#625]
"You must set a Google Maps API Key in Settings > API in order to use this feature."
Why Google Maps API Key is needed? Maps part?
If it is not needed, please remove this message for this module, or add an option to disable it, disable the "Near me settings" part and Map application part.

**Comment by Slicit** [comment]
Near me / Nearby will automatically be enabled/disabled depending on user location settings (phone)

However, FanWall uses google maps api key for the Map also

**Comment by Slicit** [comment]
Theses options will be fixed/improved in 4.17.0 in Social Wall module.

NewsWall & FanWall will be deprecated.
