### ISSUE TITLE
OpenStreetMap API

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#627]
It is possible to add OpenStreetMap?
- https://www.openstreetmap.org/
- API: https://wiki.openstreetmap.org/wiki/API

**Comment by userdevel** [comment]
yes, it it an alternative to Google Maps API, my previous ticket gives you idea!

**Comment by Slicit** [comment]
We won't add it, this will add way too much work and API management, doubling all the work (and issues, support, etc...) about the API's, Google Maps is used everywhere ....

**Comment by Neustradamus** [comment]
@Slicit Please note that OpenStreetMap is open-source and free :)
- https://www.openstreetmap.org/about

**Comment by Neustradamus** [comment]
@Slicit: Several month after, more and more companies use OpenStreetMap.

Recently, Qwant Maps uses it...

Security, confidentiality, ...

And please note that OSM API is free and it is open-source not like Google.

**Comment by Slicit** [comment]
> Google Maps is used everywhere ....

It's not about being free or open-source, we just used GMaps everywhere, etc, migrating to another map provider will imply republishing ALL apps for our customers, and will imply way too much changes, because OSM is not a drop-in replacement for google maps, we will have to rebuild everything from scratch, so again *no*

**Comment by Neustradamus** [comment]
Customers can choice proprietary or open-source, datas, security, confidentiality, and money...

I have not said you to remove Google Maps API, I have requested you to add OpenStreetMap support.

Why several companies use OpenStreetMap now?

Maybe good to do a survey about this point, I already know that several customers wait for it ;)

**Comment by Neustradamus** [comment]
@Slicit: Any news about this ticket?
