### ISSUE TITLE
Newswall / Fan Wall : How to remove a picture?

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#630]
There is "Insert a picture", there is not "Remove a picture", can you add it?

In the same time:
Why "Newswall" and "Fan Wall"?
Why not "News Wall" / "Fan Wall" or "Newswall" / "Fanwall"?

**Comment by Slicit** [comment]
In FanWall v2 in 4.17.0 you can now add/remove a picture (from the editor, or from the app directly)

**Comment by Slicit** [comment]
Theses options will be added in 4.17.0 in Social Wall module.

NewsWall & FanWall will be deprecated.
