### ISSUE TITLE
Fan Wall: Only 1 layout compared to Newswall

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#631]
It is possible to have same layouts than Newswall for Fan Wall?

**Comment by Slicit** [comment]
FanWall v2 in 4.17.0 will still have a single layout to start.

Design will have two options `list` & `card`

If there is more demand, we will consider adding new layouts after that point.

![list-post](https://user-images.githubusercontent.com/4389060/59926093-cf17c900-9439-11e9-8af0-0c18823d59a7.png)
![list-comment](https://user-images.githubusercontent.com/4389060/59926095-d17a2300-9439-11e9-820e-81b669d28f9b.png)
![card-post](https://user-images.githubusercontent.com/4389060/59926100-d3dc7d00-9439-11e9-8665-1c83fcce1579.png)
![card-comment](https://user-images.githubusercontent.com/4389060/59926102-d5a64080-9439-11e9-9ba4-17c1172a6cd8.png)

**Comment by Slicit** [comment]
Theses options will be added in 4.17.0 in Social Wall module.

NewsWall & FanWall will be deprecated.
