### ISSUE TITLE
Newswall / Fan Wall : "Hide/Show this info" same icon (not easy to know)

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#632]
"Hide this info" and "Show this info" have same icon, it is not easy to know without move the cursor on all eye icons.

Can you add colors?

In Job module, there are possibilities to "Enable/Disable company", "Enable/Disable place", "Enable/Disable category") : There are 2 different icons.

**Comment by Slicit** [comment]
This is not relevant anymore.

**Comment by userdevel** [comment]
It is possible to have 2 different icons, it is already done for Job module...

How it is possible to know what are hidden and showed posts?

**Comment by Slicit** [comment]
I said it's not relevant anymore, if you did read every else answer I gave about the new "Social Wall (Fan Wall v2)" feature.

![Screen Shot 2019-06-27 at 14 57 27](https://user-images.githubusercontent.com/4389060/60268100-ea784d80-98eb-11e9-9dc6-118b16b323d1.png)
![Screen Shot 2019-06-27 at 14 57 30](https://user-images.githubusercontent.com/4389060/60268101-ea784d80-98eb-11e9-97d1-6b63c2d029ac.png)
![Screen Shot 2019-06-27 at 14 57 32](https://user-images.githubusercontent.com/4389060/60268102-ea784d80-98eb-11e9-8968-82b5afa9430b.png)

**Comment by userdevel** [comment]
Nice if there are 2 icons:
- One for "Publish post"
- One for "Unpublish post"

Modify and remove buttons have tooltips too?

Please look that there is a problem with "Pub. date"!
26/06/2019 vs 06/26/2019

Do not forget that I have created tickets about date/time problems which have not the same settings in all the code.

In the same time, it is possible to have seconds?

It will have for Newswall too?

**Comment by Slicit** [comment]
@userdevel why not checking the Github codebase in branch release/4.17.0 and see by yourself?

GitHub is a place for contribution, this is not a support channel, you are here to help and propose fixes, you can do so by forking the repository, adding things in your code, then submitting us what's changed for review.

So please, do me a favor!
