### ISSUE TITLE
Newswall / Fan Wall : Disable comments / likes

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#633]
There are not options to:
- Disable comments (old or/and new)
- Disable likes (old or/and new)
By publication or generally.

There are:
- On main page of the layout 1 near date/time
- On publications, if options are disabled, it will be possible to do not show:
   - "Click here to log-in" section
   - "No comments for now" section
   - "Comment" section
   - "Like" section

**Comment by Slicit** [comment]
We will review after 4.17.0 release, if some are implement or will be.

Thanks.

**Comment by Slicit** [comment]
Theses options will be added in 4.17.0 in Social Wall module.

NewsWall & FanWall will be deprecated.
