### ISSUE TITLE
Newswall / Fan Wall : Users can not edit/remove his comments and likes

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#634]
Users can not edit or remove his comments and his likes, it is possible to add an option to enable or disable in admin?

In the same time: Admin can not edit (moderate) user comments; admin can only remove comments.

**Comment by Slicit** [comment]
Scheduled for 4.17.0

User can like / unlike

![tLMiG0PLU1](https://user-images.githubusercontent.com/4389060/59925705-f9b55200-9438-11e9-8df6-f5b3fe0cc0b7.gif)

User can post / delete his comments

![idalrPvSW4](https://user-images.githubusercontent.com/4389060/59925795-28332d00-9439-11e9-8216-033cb867f37e.gif)

**Comment by userdevel** [comment]
In this .gif, we do not see the modify button (only flag) for comments (example "test").
It is possible to add the removal "x" button in the same time for have "flag", "modify", "remove"?

There is a log file for admin/moderator?

Example, a guy adds a "bad comment" or a "bad post" and it is removed by himself or an admin/moderator?

If a comment (or post) has been modified, we see previous versions?

**Comment by Slicit** [comment]
Theses options will be fixed/improved in 4.17.0 in Social Wall module.

NewsWall & FanWall will be deprecated.
