### ISSUE TITLE
Move "module" pages in administration : Problem

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#636]
On my window, there are 7 modules, other 7 modules after, etc.

Example: When I try to move a module of the second part (8th position), I would like to move to 10th position, I click on left top of the module <-> but my cursor moves to the 1st module.

Can you solve it?

**Comment by Slicit** [comment]
Fix is scheduled for 4.16.11
https://github.com/Xtraball/Siberian/commit/069c9bab05ef72694bdaebb4d621907a5a5b49cd

Short story, when `clicking` on the move icon, there was a trigger to clear `any` current search, then slide to the correct page (means the one where the current item is) but it was sliding to the first page every time.

**Comment by userdevel** [comment]
Thanks, we will see when 4.16.11 will be released :)
