### ISSUE TITLE
Wordpress : "Manage WordPress", "Add a query" and "Manage queries" sections are opened by default

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#637]
"Manage WordPress", "Add a query" and "Manage queries" sections are opened by default, can you close this section by default like other module?

In the same time: "Manage WordPress" has not the icon at right in the same time "v".

**Comment by SiberianCMS** [comment]
[This issue was closed for being inactive for a too long period]
If you think this issue is relevant, please re-open it.
