### ISSUE TITLE
Newswall / Fanwall Models: Add Ability To Include Media In Posts (Videos & Audio)

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#64]
Currently (v4.3.1) on the Newswall and Fanwall Models, except for images, there isn't a way to display media. 

A great addition would be adding the ability to embed YouTube posts, mp3 audio files, and mp4 video files.  Doing so will make the posts in the Newswall/Fanwall more entertaining and useful (helps to drive and retain users) .

**Comment by SiberianCMS** [comment]
Youtube video will be great and we already think about it. For MP4 and MP3 it will be very resources and bandwidth consuming.

**Comment by clifton11221** [comment]
I'm very glad to hear that you're thinking about YouTube.  That would be fantastic!

**Comment by clifton11221** [comment]
Please also make it so that links can be added.  

Currently the field size text size is 255.  This is too restrictive and a lot of comments get cutoff.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?

**Comment by awakebrasil** [comment]
Any news after more two years?
