### ISSUE TITLE
Audio : Custom playlist problem

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#640]
I have created 3 custom playlists (+pictures) :
- 0 song, one song and two songs
- song : 19 seconds, in the playlist, I see :
   - Test : 0 tracks - 00 (0 Tracks? What 00?)
   - Test : 1 track - 19 (What 19?)
   - Test : 2 tracks - 38 (What 38?)

Infos:
- Artist: Test
- Album: Test
- One song: Test

Example, in "Manage content" -> My playlist 
- I see: "Test de Test (1 title)" <-- "de"?

I click on it, I see now:
- "Test by Test"

In the same window, I can not see the .mp3 link of the song, I can not edited the song.

And I see:
- "Add a track" at left
- "1 title" at right

Why?

Please note, if the playlist is empty, there is "0 titles" <-- "S"

No tooltip on the pen and the "x" (missing in several modules)

In more, in "Manage content", there is not hide option like publications in Newswall/Fan Wall.

I think it is possible to add the comment and like parts too.

**Comment by SiberianCMS** [comment]
[This issue was closed for being inactive for a too long period]
If you think this issue is relevant, please re-open it.
