### ISSUE TITLE
Discount / QR Coupons : Bad icon for "Create a new Discount"

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#641]
In "Discount" and "QR Coupons" module admin, "Create a new Discount" has not the good "+" icon, can you solve it?

No tooltip on "view", "modify", "delete" icons.

For be like other modules, it is not better to have "Add content" instead of "Create a new Discount"?

**Comment by SiberianCMS** [comment]
[This issue was closed for being inactive for a too long period]
If you think this issue is relevant, please re-open it.
