### ISSUE TITLE
Several sections of modules without "v" icon and opened by default

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#642]
Several sections of modules without "v" icon and opened by default, here all without "v" (there are several sections opened by default in more):
- Facebook: "Facebook"
- Wordpress: "Manage WordPress", "Background, "Manage WordPress"
- Fan Wall: "Near me settings"
- Link: "Information"
- Links: "Your links", "Settings & Options", "Background"
- Discount: "Design", "Background"
- QR Coupons: "Design", "Background"
- Maps: "Maps configuration", "Settings & Options", "Background"
- Contact: "Contact information", "Settings", "Background"
- Custom Page: "Custom page"
- Form: "Settings", "Manage fields", "Results", "Export", "Background"
- Booking: "Settings", "Background"
- Catalog: "Manage Catalog & Products", "Design", "Background"
- Commerce: "My Orders", "Manage User Field", "Connected Printers", "Search", "Tip", "Guest Order"
- Weather: "Weather information"
- Topics: "Page description"
- Radio: "Information"
- RSS Feed: "Design", "Background", "Settings"
- Twitter: "twitter"
- Folder: "Manage Folders", "Design", "Background", "Manage Folders"
- Job: "Configuration"
- My Account: "Settings", "Design", "Background"
- Magento: "Magento"
- Padlock: "Restrict Access"
- Prestashop: "Prestashop"
- Shopify: "Shopify"
- Source Code: "Source Code"
- Volusion: "Volusion"
- Privacy Policy has no section, one will be good no?

We can see several sections on the main page of the module, and some have tabs, not same for all...

**Comment by SiberianCMS** [comment]
[This issue was closed for being inactive for a too long period]
If you think this issue is relevant, please re-open it.
