### ISSUE TITLE
Calendar : Picture size?

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#644]
The size of the picture of an event is not specified in Calendar module.
Can you add the recommend values like other place?

**Comment by Slicit** [comment]
We will when calendar will be reviewed/updated, actually it's a very old feature, and we haven't done any refactoring, so it's why the recommend doesn't appear like other most recent modules.

**Comment by userdevel** [comment]
Add the size in the tab name like other is not possible?
