### ISSUE TITLE
Missing tooltips on several icons in all modules

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#647]
Missing tooltips on several icons in all modules
It works for:
- Newswall: "Hide this info", "Show this info", "Delete this info" (missing for: view, comments, modify)
- Fan Wall: "Hide this info", "Show this info", "Delete this info" (missing for: view, comments, modify)

Nothing in other modules:
- Set Meal
- Discount
- QR Coupons
- Places
- Contest
- In-App Messages
- Form
- Calendar
- Catalog (+ "Add a new")
- Topics
- RSS Feed
- Commerce
- Audio
- Job (There are only "Disable company", "Disable place", "Disable category")
- Loyalty Card

**Comment by userdevel** [comment]
- Social wall: "Unpublish post", "Publish post", "Pin post", "Unpin post" (missing for: modify, delete) <- view, comment have been removed, it will be in Newswall and Fan Wall.

**Comment by Slicit** [comment]
> Fixed for 4.17.6
~Social wall: "Unpublish post", "Publish post", "Pin post", "Unpin post" (missing for: modify, delete) <- view, comment have been removed, it was in Newswall and Fan Wall.~

> Some other just don't have tooltips, that's it.
