### ISSUE TITLE
Facebook module : Page Public Content Access

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#659]
After added Facebook API in /application/settings_apis, we enter the page number or username in the Facebook module, we have this error:

(#10) Object does not exist, cannot be loaded due to missing reviewable feature 'Page Public Content Access', or does not support this operation. To use 'Page Public Content Access', your use of this endpoint must be reviewed and approved by Facebook. To submit this 'Page Public Content Access' feature for review please read our documentation on reviewable features: https://developers.facebook.com/docs/apps/review.

The doc are not good:
- https://doc.siberiancms.com/knowledge-base/how-to-create-api-keys/
- https://doc.siberiancms.com/knowledge-base/facebook-page/
- https://doc.siberiancms.com/knowledge-base/facebook-page-integration-does-not-work/

I think it is only for Facebook login, can you update it?
Several options must be added like "Page Public Content Access"?
If yes, we need a video for validate (facebook request it), can you add a generic video?

What is managed exactly in this module?

There are:
- Instagram Public Content Access
- Ads Management Standard Access
- ads_management
- ads_read
- Groups API
- Page Public Content Access
- Live Video API
- Page Mentions
- user_videos
- user_tagged_places
- user_posts
- user_photos
- user_location
- user_link
- user_likes
- user_hometown
- user_gender
- user_friends
- user_events
- user_birthday
- user_age_range
- read_page_mailboxes
- read_insights
- publish_to_groups
- publish_pages
- pages_manage_instant_articles
- pages_manage_cta
- manage_pages
- leads_retrieval
- groups_access_member_info
- business_management
- publish_video
- instagram_manage_insights
- instagram_manage_comments
- instagram_basic

**Comment by Slicit** [comment]
We can't add a `generic video` you need to create an Test API key, and create a demo video on purpose, for each application, that's what Facebook wants by now.

**Comment by userdevel** [comment]
How we can do a video if we can not have the API works without errors?

**Comment by Slicit** [comment]
You can use the API in development mode, with "restricted access" they allow you to test your API before going into production
