### ISSUE TITLE
Unified Homepage option problems

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#662]
On: Editor -> Design -> Unified Homepage: /application/customization_design_style/edit
- Hide iOS status bar: disabled -> Not showed on iPhone 5
- Hide Android status bar: enabled -> Not hidden on Android

No refresh for:
- Use the homepage image as background in all features
- Hide iOS status bar
- Hide Android status bar

**Comment by userdevel** [comment]
@Slicit Have you seen?

**Comment by Slicit** [comment]
Yes I see everything, but anyway if you're talking about the visibility of this option in the "app overview" in the right side of the editor, this will be soon removed from here.

**Comment by userdevel** [comment]
Why removed?
The app preview is really important!

**Comment by Slicit** [comment]
Never said we will remove the overview, we will move to a single app preview as default, and more options presented in another way.
