### ISSUE TITLE
Commerce: No price showed, only product description (if no product price because product format prices)

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#667]
In the Commerce module administration: No price in "My Product" section if there is "Product formats" enabled.

In the app: There is not "Product price" in Category section if there is "Product formats" enabled and it is replaced by "Product description".

It is not possible to have in the app, the product price and the product description?
An option to enable one or two in module admin?
Of course for product price or product format prices.

**Comment by userdevel2** [comment]
This bug has been solved?
What is the version?
I see a lot of tickets closed.
