### ISSUE TITLE
ionic update

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#669]
Last version here:
- 4.4.2 (2019-05-22) : https://github.com/ionic-team/ionic/releases
- very old 1.3.x, last 1.3.5: https://github.com/ionic-team/ionic-v1

**Comment by Slicit** [comment]
Ionic 1 to Ionic 2 involves a lot of changes (such angularjs > angular) it's not possible to upgrade without recoding everything.

I'm not saying we won't at some point migrate, but we won't upgrade, we have to keep version safe.

Moreover, as said many times, most of our base tools, are all forked and custom, EVEN Ionic 1 is customized to our needs.
