### ISSUE TITLE
Cordova update

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#672]
Last versions here:
- Android 8.0.0 (2019-02-13) : https://github.com/apache/cordova-android/releases
- iOS 5.0.1 (2019-04-18) : https://github.com/apache/cordova-ios/releases
- Browser 6.0.0 (2019-02-01) : https://github.com/apache/cordova-browser/releases

**Comment by Slicit** [comment]
Same as for Ionic 1.
Our Cordova stack is "Siberian-Cordova" which means we have our own forks with custom changes, and we upgrade only about every 6 months, keep in mind we are building a CMS, not a single App builder, were you can build each app differently, when you run Siberian, all your apps run at the same time, with the same version.

We are not Cordova, we are not Ionic.

If we had only the SAE edition, maybe we could've gone further and choose to upgrade more regularly, but with MAE & PE the cost of changing frameworks more often is breaking lot of apps and customers.
