### ISSUE TITLE
Newswall / Fan Wall : Pin to top a publication

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#680]
Can you add a function to pin to top a publication in the Newswall and Fan Wall modules?

**Comment by Slicit** [comment]
This improvement is scheduled for the FanWall v2 which will be released with 4.17.0 early July.

![pinned-post](https://user-images.githubusercontent.com/4389060/59925436-69770d00-9438-11e9-887a-2ad11c51762c.png)

**Comment by Slicit** [comment]
Closing as not relevant anymore.

Will be added in 4.17.0 in Social Wall module.

NewsWall & FanWall will be deprecated.
