### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [Xtraball/Siberian#681]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/Xtraball/Siberian/blob/master/package.json#L12

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

Same for `https` (https://nodejs.org/api/https.html).

**Comment by Slicit** [comment]
Removed from develop branch.

Thanks.
