### ISSUE TITLE
Pop up for instructions how to adjust battery optimiser to off for audio services 

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/Siberian#683]
Hi  over year ago we have been asking for optimiser to be turned off in android for radio app, obviously no one has found a way to fix the problem,  so can we have a one time pop up on install to a link in settings of the phone to manually turn off the optimiser for that app being installed as this makes the RADIO PLAYER and the app Portals look a bit amateurish just leaving this bug in the Radio Player after all this time since android 6,7.

Other sites have done this to get over the temporary problem although this has not  been a temporary problem by a long shot.

Cheers

**Comment by Slicit** [comment]
I invite you to check our roadmap, this thing with the battery optimisation is being adressed in 4.17.0 which will be released this week. 
https://www.siberiancms.com/community/d/745-roadmap-4-16-4-17-4-18
