### ISSUE TITLE
Pull request?

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#684]
It will be added? @maniwebertech
- https://github.com/Xtraball/Siberian416/pull/21

**Comment by Slicit** [comment]
In MCommerce we only do changes for critical issues, this is one is unlikely to be merged one day, thanks.

**Comment by Neustradamus** [comment]
@SiberianCMS @Slicit @userdevel: I have seen that MCommerce will be updated for 4.18.0, this PR has been integrated?
-> https://github.com/Xtraball/Siberian416/pull/21/files
