### ISSUE TITLE
MAE - v4.17.0 android 9 apps u/s not installing or greayed out

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/Siberian#686]
Android 9 apps either not installing  (white screen of death)  or if they do install they are all greyed out, looks like there could be possibly be selinux permission problems within 9, put the app as an html5 in chrome all works fine so not firwall etc related or php version as I have installed 7. 2 and still no good, this is by apk system and your own fastlane bash  system, not tried in my android studio as that may confuse things but its definitely not working guys.
cheers
ps the bypass batt optimiser seems to work fine which is good up to android 8.1.

**Comment by rogerdavis198** [comment]
Update to 4.17.0
Will not make in External Android studio this end. coming up with Duplicate files in external studio, adjusted to ignore this and still will not make apk , seems like anything in 4.8.3 tools does not try and make properly with the output from gradle being incompatable with the new tools.

Problem 2.
any brand new apps made with 4.17.0 too will not make apk on internal or your fastlane system.
Hope this may help you as seems its gradle that has the problem with its output on this one.



Cheers

**Comment by w3sbari** [comment]
Idem, screen white e overlay loading to infinite.. Xtraball Where is a solution for Android 9?
