### ISSUE TITLE
Social wall problems

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#687]
Refresh page problem:
- Page name not updated, no refresh...
- When we pin a post, there is no refresh, it is always "Pin post" (same red icon), it must be "Unpin post" with other icon (green).
- When we unpublish a post, the icon change (nice), there is no refresh and if we "publish post" after it, the icon does not change.

App preview problem:
- https://github.com/Xtraball/Siberian/issues/661

Date/time problem like other:
- https://github.com/Xtraball/Siberian/issues/648

Tooltips problem:
- https://github.com/Xtraball/Siberian/issues/647

Missing buttons (it was in Newswall and Fan Wall)
- view
- comment

Text change requests:
- https://github.com/Xtraball/Siberian/issues/657
- ADD A POST -> ADD CONTENT
- SAVE -> OK
- MANAGE POSTS -> MANAGE CONTENT

Linked to date/time options:
- https://github.com/Xtraball/Siberian/issues/561
- https://github.com/Xtraball/Siberian/issues/566

**Comment by Slicit** [comment]
Page name not updated, no refresh...

Already fixed, others will come.

**Comment by userdevel** [comment]
@Slicit: Not solved in 4.17.1.

Page name changed in administration:
- no app preview refresh
- no page name update

When we add a post:
- no app preview refresh

**Comment by userdevel** [comment]
@Slicit: Page title in app previewer is always not solved in last current version: 4.17.4.

And there are 3 empty "buttons" under "Social Wall" title.

Subtitle part is missing (Fan Wall and Newswall are OK)
CKEditor is different from Fan Wall and Newswall

You move Newswall and Fan Wall in a new module "Social wall" (Fan Wall v2) but you remove several points!

Old Layouts from Newswall are missing:
- Layout1
Title
Subtitle
Text
Picture
Date/Time/Comments/Likes

- Layout2
Picture
Title
Subtitle

- Layout3
Picture
Title
Subtitle

- Layout4
Picture
Number - Title
Subtitle

**Comment by Slicit** [comment]
It's new feature, we didn't intended to replace all old layouts, we will probably add some new in the future, but for now.
It's not because this feature is intended to replace old newswall/fanwall, that it should have the exact same look & feel.

--

> Fixed for 4.17.6
~When we pin a post, there is no refresh, it is always "Pin post" (same red icon), it must be "Unpin post" with other icon (green).~

**Comment by Slicit** [comment]
> Already fixed
~Page name not updated, no refresh...~

But, the page title will not be updated "live" in the side overview, you have to refresh the page, like most of all features.

**Comment by Slicit** [comment]
> Nope
Linked to date/time options:

#561
#566

> Nope
Text change requests:

#657
ADD A POST -> ADD CONTENT
SAVE -> OK
MANAGE POSTS -> MANAGE CONTENT

> Nope (maybe later, but nope)
Missing buttons (it was in Newswall and Fan Wall)

view
comment

> It's working as intended. > NOPE
Date/time problem like other:

#648

> That's a general way beyond complex task to rethink completely, it's beyond all scope, being rethinked, but way beyond anything close to be 100% working, it's really complex to have perfect sync between Editor/App preview.
App preview problem:

#661

**Comment by userdevel** [comment]
@Slicit: Problems:

- Page name changed in administration:
-- no app preview refresh (like other features)

- When we update:
-- no app preview refresh

Note: No problems in Newswall and Fan Wall

- Missing layout
- No import from Newswall and Fan Wall
