### ISSUE TITLE
Audio Player Module Needs UI Fix When For When There Aren't Multiple Albums

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#69]
Currently, if I add a list of mp3 songs to the Audio Player module, the end-user has to make 4 clicks simply to get to the list of songs and select one, and then another 4 clicks to exist out.  This issue exist if audio is added from iTunes, etc as well.

The problem is a consequence of the Module being created to handle multiple albums.  In a way this is a good thing but if there aren't multiple albums, the UI is cumbersome for the end-user and they have to make unnecessary clicks just to hear the music.

There needs to be an option in the player that we can select when adding the audio that will simply display the single list of audio files (if there aren't albums).  This way when used by the end-user, as soon as they click the Audio button, they will be taken directly to the music.

![click_01](https://cloud.githubusercontent.com/assets/21089972/18029326/1276b6a4-6c63-11e6-80f7-048dc1499ea7.png)
![click_02](https://cloud.githubusercontent.com/assets/21089972/18029323/1272c6fc-6c63-11e6-9923-95bcc67e571c.png)
![click_03](https://cloud.githubusercontent.com/assets/21089972/18029325/1274b138-6c63-11e6-92ce-8fa78530a5b6.png)
![click_04](https://cloud.githubusercontent.com/assets/21089972/18029324/1273e0fa-6c63-11e6-80d0-8ad47dc12af5.png)

**Comment by alexyves** [comment]
It's clear :)

**Comment by gonzoradio** [comment]
can it just be made so that the default opening screen of the audio module goes to 'albums' instead of playlists?  that would solve the issue i think.  most music apps don't default to playlists, in my experience.

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?

**Comment by SiberianCMS** [comment]
Audio player is scheduled to be completely replaced & rebuilt*
