### ISSUE TITLE
Social wall VS Social Wall VS SocialWall name

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#691]
By default in 4.17.0:
- Page name: "Social wall"
- App preview: "Social Wall"

It will be nice to be coherent no?

I think the best name is "Social Wall"

It must not like previously Newswall and Fan Wall ;)

I have opened a ticket about the refresh problems for this module and other...

**Comment by Slicit** [comment]
You can change the name to what you want in editor.

**Comment by userdevel** [comment]
No it does not work in 4.17.4!

By default, I have seen in several modules:
- Newswall
- Fan Wall
- Social wall
