### ISSUE TITLE
Impossible to move contents (only creation order) in all modules (except exception)

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#692]
Impossible to move contents (only creation order) in all modules (except exception)

Examples:
- https://github.com/Xtraball/Siberian/issues/689
- https://github.com/Xtraball/Siberian/issues/690
- ...

It is possible for:
- Audio (front)
- Catalog (nice icon, front)
- Custom Page (behind)
- Form (front)
- Links (nice icon, behind)
- RSS Feed (front)
- Topics (front)

But it will be nice to have the same for all:
- Icon: like Catalog and Links, no?
- Placement: in front or behind

**Comment by Slicit** [comment]
That's how most work, issues are for single "fix/improvement" we won't cover it here, we will take care of what's needed if we do refactoring on these modules.
