### ISSUE TITLE
Sae/Mae problem in android 9

### ISSUE THREAD

**Issue by w3sbari** [Xtraball/Siberian#695]
I have tested in sae and Mae all apps generated or compilate with android studio, but all apps don t run in android version 9. In version 8 running. Do you have the chance to test your Siberian-generated apps directly on one or more phones with Android 9?

**Comment by w3sbari** [comment]
In android 9 appaer overlay loading to infinity, white screen of death or greyed out

**Comment by SiberianCMS** [comment]
[This issue was closed for being inactive for a too long period]
If you think this issue is relevant, please re-open it.
