### ISSUE TITLE
Android 9 Radio feature not playing 

### ISSUE THREAD

**Issue by Carl397** [Xtraball/Siberian#696]
I have tested Nokia 8 and Samsung A9 with android 9.
V4.17.3 : Radio open but no sound.

**Comment by rogerdavis198** [comment]
See v4174

**Comment by Carl397** [comment]
The test was done on the v4.17.4
Nokia 8 and Samsung A9 both phone have android 9 on.

**Comment by rogerdavis198** [comment]
https://github.com/Xtraball/Siberian/issues/700

Please check link out ref audio streams  web pages etc

**Comment by Carl397** [comment]
Please  see link below: 
http://zas3.ndx.co.za/proxy/radiokc?mp=/stream

The link works in the web player and android 8 and below.
Playing on the desktop.

**Comment by userdevel** [comment]
I have tested an HTTPS radio streaming link, it does not work in the app preview too!
It is not only Android 9.

**Comment by SiberianCMS** [comment]
[This issue was closed for being inactive for a too long period]
If you think this issue is relevant, please re-open it.
