### ISSUE TITLE
Ver 4.17.4

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/Siberian#700]
We need (plain text true) buttons on radio and web links as android 9 defaults to https on all links, this is what all the other developers are doing to get over this problem, the http is not a big problem if you have web space set up to https, but the audio link to https is going to be a right pain for everyone unless you can build a proxy server into the scripts but that will cause big load problems for Siberian, best to get the option of (PLAIN TEXT TRUE) button for all parts of the apps that would be affected by this problem. Thanks

**Comment by userdevel** [comment]
I have tested an HTTPS radio streaming link, it does not work in the app preview too!
It is not only Android 9.

**Comment by Carl397** [comment]
What other versions don't work?
On my side the previewer it work.

**Comment by userdevel** [comment]
It works, mistake from me!

**Comment by Carl397** [comment]
Is there a better way to test more Android 9 versions?
