### ISSUE TITLE
Bad EOL in several files

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#702]
There are bad EOL in several files (WINDOWS instead of UNIX), can you change it?
- \siberian\app\sae\design\design-cache.json
- \siberian\lib\vendor\bin\export-plural-rules
- \siberian\lib\vendor\bin\export-plural-rules.php
- \siberian\var\apps\browser\dist\templates.js
- \siberian\var\apps\ionic\android\app\src\main\assets\www\dist\templates.js
- \siberian\var\apps\ionic\ios\Pods\Headers\Private\GoogleToolboxForMac\*.*
- \siberian\var\apps\ionic\ios\Pods\Headers\Private\nanopb\*.*
- \siberian\var\apps\ionic\ios\Pods\Headers\Private\Protobuf\*.*
- \siberian\var\apps\ionic\ios\Pods\Headers\Public\GoogleToolboxForMac\*.*
- \siberian\var\apps\ionic\ios\Pods\Headers\Public\nanopb\*.*
- \siberian\var\apps\ionic\ios\Pods\Headers\Public\Protobuf\*.*
- \siberian\var\apps\ionic\ios\www\dist\templates.js
- \siberian\var\apps\overview\dist\templates.js

**Comment by Slicit** [comment]
Not an issue. any IDE handle seamlessly.
