### ISSUE TITLE
Xtraball SASE?

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#703]
There are currently 5 "Xtraball SASE" in files:
- https://github.com/Xtraball/Siberian/blob/master/ionic/platforms/android/app/src/main/assets/www/js/filters/filters.js
- https://github.com/Xtraball/Siberian/blob/master/ionic/platforms/browser/www/js/filters/filters.js
- https://github.com/Xtraball/Siberian/blob/master/ionic/platforms/ios/www/js/filters/filters.js
- https://github.com/Xtraball/Siberian/blob/master/ionic/www/js/filters/filters.js
- https://github.com/Xtraball/Siberian/blob/master/siberian/var/apps/ionic/android/app/src/main/assets/www/js/filters/filters.js

**Comment by Slicit** [comment]
In fact it's only present once, but the others are "duplicated assets" will remove it.

**Comment by Neustradamus** [comment]
@Slicit: One month after, always here at this date: https://github.com/Xtraball/Siberian/search?utf8=%E2%9C%93&q=Xtraball+SASE&type=

**Comment by Neustradamus** [comment]
@SiberianCMS: Always here!
I think that several tickets have been closed without solutions, no?

**Comment by Neustradamus** [comment]
@SiberianCMS @Slicit: It will be always here for 4.18.0?
At this date: https://github.com/Xtraball/Siberian/search?utf8=%E2%9C%93&q=Xtraball+SASE&type=

>  * @version 4.15.7

**Comment by Neustradamus** [comment]
@SiberianCMS: Can you realize this little change?
It is your company.
