### ISSUE TITLE
Why modified?

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#704]
I work for Zend 1.12.20 (security point and last version since several years ago) for Siberian.

I see a modified file from you:
- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Mobile/Push/Apns.php#L39
>     const SERVER_SANDBOX_URI = 0;
>     const SERVER_PRODUCTION_URI = 1;
>     const SERVER_FEEDBACK_SANDBOX_URI = 2;
>     const SERVER_FEEDBACK_PRODUCTION_URI = 3;
and
>         'ssl://gateway.push.apple.com:2195',
>         'ssl://gateway.push.apple.com:2195',
>         'ssl://feedback.push.apple.com:2196',
>         'ssl://feedback.push.apple.com:2196'
It must be:
>         'ssl://gateway.sandbox.push.apple.com:2195',
>         'ssl://gateway.push.apple.com:2195',
>         'ssl://feedback.sandbox.push.apple.com:2196',
>         'ssl://feedback.push.apple.com:2196'
0 and 2 are SANDBOX.
Source: https://github.com/zendframework/zf1/blob/master/library/Zend/Mobile/Push/Apns.php

**Comment by Slicit** [comment]
Same here, custom zf, we only use prod, not sandbox.
