### ISSUE TITLE
Please remove old dead part

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#705]
Dead:
- InfoCard
- DeveloperGarden
- Nirvanix
- Technorati

**Comment by Slicit** [comment]
Can you point me where these things are? :)

**Comment by Neustradamus** [comment]
Zend Framework 1, I am looking for have a 1.12.20 base for Siberian CMS.
It is in progress, I have requested you why have you changed some parts in old 1.12.3, some files are from next version 1.2.x and more... but some codes have been added, I would like to know why?

https://github.com/Xtraball/Siberian/issues/708

Please reply me, I work for have a best secure Siberian CMS for all admin servers.

**Comment by Slicit** [comment]
I just repeat, we have our own custom/fork ZF1, with latest versions merged/etc ..
As long as it's safe and there is no security or critical issue we have no need to upgrade it.

**Comment by Neustradamus** [comment]
@Slicit: One month after, any news for removal old parts?

**Comment by Slicit** [comment]
> @Slicit: One month after, any news for removal old parts?



> I just repeat, we have our own custom/fork ZF1, with latest versions merged/etc ..
> As long as it's safe and there is no security or critical issue we have no need to upgrade it.

So no, we just wont, we have no reason to add/remove such things as long as it's not breaking anything.

**Comment by Neustradamus** [comment]
It is dead services... Why not to clean it?

My WIP will be announced later about the ZF1 last official version with your changes from ZF2.
