### ISSUE TITLE
Android 9 audio player

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/Siberian#706]
Hi , what are we doing about below as its good enough for apps like tune *n to do below why can we we not do it so the streams work in the player, from what i have read on the Development threads, the player must be a secure page but no need for a secure audio stream feed and that is why the below was added in 8.1 and above.

We need (plain text true) buttons on radio and web links as android 9 defaults to https on all links, this is what all the other developers are doing to get over this problem, the http is not a big problem if you have web space set up to https, but the audio link to https is going to be a right pain for everyone unless you can build a proxy server into the scripts but that will cause big load problems for Siberian, best to get the option of (PLAIN TEXT TRUE) button for all parts of the apps that would be affected by this problem. Thanks

**Comment by SiberianCMS** [comment]
[This issue was closed for being inactive for a too long period]
If you think this issue is relevant, please re-open it.
