### ISSUE TITLE
Archive the old repository and inform people to go here?

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#707]
An old space:
- https://github.com/SiberianCMS/SiberianCMS
Update the README, the description to come here and archive the very old repository.

**Comment by Slicit** [comment]
The readme already points here.

**Comment by Neustradamus** [comment]
1/ No link in description: https://github.com/SiberianCMS/SiberianCMS: "Deprecated old Version of SiberianCMS"
2/ In README: https://github.com/SiberianCMS/SiberianCMS/blob/master/README.md:
/!\ Important Note /!\
Work In Progress
NOTE: This version of Siberian CMS SAE is deprecated, the latest release moved here https://github.com/Xtraball/SiberianCMS, thank's for your upcoming support
3/ Repository is not archived.

Before to archive it, please change from README:
- "Work In Progress"
- The new repository link too

Thanks.

**Comment by Neustradamus** [comment]
@Slicit: One month after, can you archive the old repository?

In the description, add a link to the new "space" in more "Deprecated old Version of SiberianCMS" https://github.com/Xtraball/Siberian.

In the same time, to do same for https://github.com/Xtraball/Siberian416.

After, archive the repository, if you do not know how to do it: https://github.com/SiberianCMS/SiberianCMS/settings
- Repository Settings -> Danger Zone -> Archive this repository

**Comment by Neustradamus** [comment]
Any news about it?

I have seen several messages from the @SiberianCMS account.
