### ISSUE TITLE
Diff questions (WIP)

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#708]
Why these diff?

1/
- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Cache/Core.php#L152
>     /**
>      * @param Zend_Config $config
>      * @return $this
>      * @throws Zend_Cache_Exception
>      */
vs
- https://github.com/zendframework/zf1/blob/master/library/Zend/Cache/Core.php#L152
>     /**
>      * Set options using an instance of type Zend_Config
>      *
>      * @param Zend_Config $config
>      * @return Zend_Cache_Core
>      */

2/
- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Controller/Request/Http.php#L32
>  *
>  * @uses Zend_Controller_Request_Abstract
>  * @package Zend_Controller
>  * @subpackage Request
>  * @method array getFilteredParams()
>  */
vs
- https://github.com/zendframework/zf1/blob/master/library/Zend/Controller/Request/Http.php#L32
>  *
>  * @uses Zend_Controller_Request_Abstract
>  * @package Zend_Controller
>  * @subpackage Request
>  */

3/ It is not a best solution here? https://magento.stackexchange.com/questions/249737/magento-2-invalid-response-line-returned-from-server-http-2-200/265373#265373
- https://github.com/zendframework/zf1/blob/master/library/Zend/Http/Response.php#L184
>         // Set the HTTP version
>         if ($version == "2") {
>             $version = "2.0";
>         }
>         if (! preg_match('|^\d\.\d$|', $version)) {
>             require_once 'Zend/Http/Exception.php';
>             throw new Zend_Http_Exception("Invalid HTTP response version: $version");
>         }
vs
- https://github.com/zendframework/zf1/blob/master/library/Zend/Http/Response.php#L184
>         // Set the HTTP version
>         if (! preg_match('|^\d\.\d$|', $version)) {
>             require_once 'Zend/Http/Exception.php';
>             throw new Zend_Http_Exception("Invalid HTTP response version: $version");
>         }

4/
- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Locale/Format.php#L45
>                                      'disableCache'  => false,
vs
- https://github.com/zendframework/zf1/blob/master/library/Zend/Locale/Format.php#L45
>                                      'disableCache'  => null,

5/ Sandbox problem for 0 and 2?
- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Mobile/Push/Apns.php#L42
>     /**
>      * @const int apple server uri constants
>      */
>     const SERVER_SANDBOX_URI = 0;
>     const SERVER_PRODUCTION_URI = 1;
>     const SERVER_FEEDBACK_SANDBOX_URI = 2;
>     const SERVER_FEEDBACK_PRODUCTION_URI = 3;
>     /**
>      * Apple Server URI's
>      *
>      * @var array
>      */
>     protected $_serverUriList = array(
>         'ssl://gateway.push.apple.com:2195',
>         'ssl://gateway.push.apple.com:2195',
>         'ssl://feedback.push.apple.com:2196',
>         'ssl://feedback.push.apple.com:2196'
>     );
vs
- https://github.com/zendframework/zf1/blob/master/library/Zend/Mobile/Push/Apns.php#L42
>     /**
>      * @const int apple server uri constants
>      */
>     const SERVER_SANDBOX_URI = 0;
>     const SERVER_PRODUCTION_URI = 1;
>     const SERVER_FEEDBACK_SANDBOX_URI = 2;
>     const SERVER_FEEDBACK_PRODUCTION_URI = 3;
>     /**
>      * Apple Server URI's
>      *
>      * @var array
>      */
>     protected $_serverUriList = array(
>         'ssl://gateway.sandbox.push.apple.com:2195',
>         'ssl://gateway.push.apple.com:2195',
>         'ssl://feedback.sandbox.push.apple.com:2196',
>         'ssl://feedback.push.apple.com:2196'
>     );

6/ # for PHP7.2+? No better solution?
- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L26
> #require_once 'Zend/Session.php';

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L26
> require_once 'Zend/Session.php';

- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L31
> #require_once 'Zend/Db/Table/Abstract.php';

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L31
> require_once 'Zend/Db/Table/Abstract.php';

- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L36
> #require_once 'Zend/Db/Table/Row/Abstract.php';

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L36
> require_once 'Zend/Db/Table/Row/Abstract.php';

- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L41
> #require_once 'Zend/Config.php';

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L41
> require_once 'Zend/Config.php';

- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L171
>             #require_once 'Zend/Session/SaveHandler/Exception.php';

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L171
>             #require_once 'Zend/Session/SaveHandler/Exception.php';

- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L235
>             #require_once 'Zend/Session/SaveHandler/Exception.php';

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L235
>             require_once 'Zend/Session/SaveHandler/Exception.php';

- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L361
>         //return $return;
>         return true;
>     }

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L361
>         return $return;
>     }

- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L424
>             #require_once 'Zend/Session/SaveHandler/Exception.php';

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L423
>             require_once 'Zend/Session/SaveHandler/Exception.php';

- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L456
>             #require_once 'Zend/Session/SaveHandler/Exception.php';

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L455
>             require_once 'Zend/Session/SaveHandler/Exception.php';

- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L465
>             #require_once 'Zend/Session/SaveHandler/Exception.php';

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L464
>             require_once 'Zend/Session/SaveHandler/Exception.php';

- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L485
>             #require_once 'Zend/Session/SaveHandler/Exception.php';

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L484
>             require_once 'Zend/Session/SaveHandler/Exception.php';

- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L494
>             #require_once 'Zend/Session/SaveHandler/Exception.php';

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L493
>             require_once 'Zend/Session/SaveHandler/Exception.php';

- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Session/SaveHandler/DbTable.php#L503
>             #require_once 'Zend/Session/SaveHandler/Exception.php';

vs
https://github.com/zendframework/zf1/blob/master/library/Zend/Session/SaveHandler/DbTable.php#L502
>             require_once 'Zend/Session/SaveHandler/Exception.php';

...

**Comment by Slicit** [comment]
Because as said multiple times, our ZF1 is customized.

Side note: this is not an issue ...

**Comment by Neustradamus** [comment]
Please can you reply me on these points, I have not finished the ZF1 1.12.20 base for Siberian CMS.

Maybe I must to create on ticket by remark?
You have only replied me for 5th in this ticket: https://github.com/Xtraball/Siberian/issues/704.

My Work in Progress (WIP).

**Comment by Neustradamus** [comment]
@Slicit: One month after, can you reply me please about differences?

**Comment by Slicit** [comment]
> @Slicit: One month after, can you reply me please about differences?

It has no impact, it's lazy loaded with the autoloader anyway.

**Comment by Neustradamus** [comment]
I would like to understand why the little differences.
Please take few minutes to explain.
