### ISSUE TITLE
Error 500 when saving Custom Page

### ISSUE THREAD

**Issue by airtonmendonca** [Xtraball/Siberian#710]
Hello,

I'm having some issues while trying to save Custom Pages. I receive a 500 error.

Request URL:http://admin.appz2.me/cms/application_page/editpostv2
Request method:POST
Status code:
500

And the following error on my console:
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

I've already updated Siberian to 4.17.3

Hope you guys can help me.

**Comment by SiberianCMS** [comment]
Update to 4.17.9, and try again, if you still have the issue, re-open it.
Thanks.
