### ISSUE TITLE
Datas export from deprecated Newswall and Fan Wall to import in Social wall

### ISSUE THREAD

**Issue by userdevel** [Xtraball/Siberian#711]
How it is possible to export datas from Newswall and Fan Wall to import in Social wall?

**Comment by Neustradamus** [comment]
I am in the same case, export all data of these modules and then import them into the new module.

**Comment by SiberianCMS** [comment]
We probably won't do that

**Comment by Neustradamus** [comment]
How it is possible to remove old apps without continuity of service?

**Comment by Neustradamus** [comment]
@SiberianCMS @Slicit: Recall, "I am in the same case, export all data of these modules and then import them into the new module."
- Continuity of Service
