### ISSUE TITLE
Catalog Module: 'More Options' Needs To Be More Prevelant

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/Siberian#73]
In the Catalog Module, the link that opens the other Categories isn't obvious.  As a result, the app user doesn't know more Categories are available to them.

The problem is at the top right of the app, the name of first Category is displayed (instead of indicating to the app user that more options are there).

Instead of showing the first Category name on the top-right of the screen, it needs to state something like "More" or "More Options".  The name of the Category can be moved below the menu options to the left-hand-side of the screen. 

See the attached images.

![menu_01](https://cloud.githubusercontent.com/assets/21089972/18115729/a82ff6a2-6f0f-11e6-9d72-34d23b7f83d9.png)

![menu_02](https://cloud.githubusercontent.com/assets/21089972/18115728/a82fb69c-6f0f-11e6-8b22-e4d1220adfb5.png)

**Comment by alexyves** [comment]
You are totally right :)

**Comment by RoczWebDev** [comment]
Agree 100 % , I get alot of question s from users on how to use this feature

**Comment by userdevel** [comment]
@Slicit, @LikoV2: Any news after more two years?

**Comment by Anais527** [comment]
Up !!!

**Comment by SiberianCMS** [comment]
Catalog is deprecated and will not receive future updates.
