### ISSUE TITLE
App hangs on install / or opening

### ISSUE THREAD

**Issue by grafixpress** [Xtraball/Siberian#741]
We have feedback from various european regions that:
 **Siberian apps freeze during install, or dont open.**

The issue is location related. App works fine in most locations, in some not.
When the app freezes, the webapp does not open either and gives 404.
Same happens to all apps on our MAE in this moment and location.. 
Other Siberian apps show the same behaviour.
!!! At the same time and location other apps work fine.  All other websites open normally.
Pingdom test gives loading time of 1.45 sec. for the WebApp (Frankfurt). 
Webpages, hosted on the same server, being much heavyer, open normally in these conditions.
We find no crashes on Google stats.
We had various contradictory explanations from Siberian, like to much content, size of app is not relevant because init times out, only a minority is hit by the issue, but
We are down from 4.8 stars to 2.3 since June.

All this above indicates, that even the WebApp can´t connect to the system in poor internet conditions, where all other apps and webpages work fine.
This is systemic.

**Comment by SiberianCMS** [comment]
If app freezes during install or don't open:
1. APK is bad, must rebuild a fresh one, and test it before publishing to store.
2. Apps have way too much content and reaches the timeout (either from slow internet connection, or poor network)

**Comment by grafixpress** [comment]
Please read the post.

It is not APK related. WebApps also time out / dont´t connect.
Large and small apps behave equally.
It is not an Android issue, since IOS app doesn`t open either, nor the WebApps.

Please read the post.

Thank you

**Comment by SiberianCMS** [comment]
This can be a lot of mixed things, maybe a module affecting only Android, we saw that on some instances, it's never easy to handle such random issues, moreover when it's working nicely when our team tests it

**Comment by grafixpress** [comment]
"maybe a module affecting only Android" 
**It is not only Android, it is already the CMS! And it is not a random issue, it can be reproduced regulary in the right location**
Please read the post.
This may be irrelevant for apps with a 50 downloads.
We have a 5 digit number of downloads. 
Please consider, if only some of the failed installs result in a negative response,
it kills the project.

**Comment by SiberianCMS** [comment]
No the problem is, it's related to your Siberian installation, most of the others haven't such issues, which leads to think it's maybe a module on your Siberian which affects/breaks something

**Comment by grafixpress** [comment]
We have a production MAE installation and a SAE Test Installation in different accounts.
I have uninstalled all 3 extra modules, so the installation is basic.
Both WebApps show the same behaviour.

**Comment by SiberianCMS** [comment]
And do you encounter the same behavior with apps from other Siberian?

**Comment by grafixpress** [comment]
Yes.

**Comment by SiberianCMS** [comment]
Will let you continue that on the support desk, it's dead end.

**Comment by grafixpress** [comment]
Can you explain why a WebApp loads fast in Frankfurt 1.45 sec. but times out in other locations, where all other webpages load fine?
There must be some sort of "misunderstanding" using certain Providers like O².

**This is only a thought**: The connection is (was before yesterdays update) not a forced SSL.  HTTP pages seem to be rejected by O². We got a message saying unsecure line, first, than the 404. in these conditions the app won´t install / load, of course.

**Comment by SiberianCMS** [comment]
HTTPS is highly recommended, and as said, yes the o2 network can enforces https, most of the mobile network providers do have their own proxies, so it can be this, and your apps loads very fast on our devices/mobile networks, with no issues at all, that's why I said, it's complex matter and regards tickets, not the Open-Source part of the project.

**Comment by grafixpress** [comment]
I heartily disagree, 
This is not an installation issue, nor a service matter. It is systematic.
You must have had a reason to build in forced SSL in the last update from yesterday :-)

**Comment by SiberianCMS** [comment]
@grafixpress If you had read the release note, you would have known the reason.

And if it's from the mobile network provider, it's for sure systematic.

**Comment by grafixpress** [comment]
Come on now,
You know the release notes better than me, and you didn´t come up with this either.
I have set all my webpages to forced https, this gave me the idea. And maybe it is wrong.
Anyway. Let´s see what happens.

**Comment by SiberianCMS** [comment]
https://updates02.siberiancms.com/release-notes/all/index.php?v=4.17.6

Which is pretty clear, WHY

```
CONFIGURATION > GENERAL IMPORTANT
- YOU MUST HAVE A VALID HTTPS CERTIFICATE

- Enforces use_https to true, Android 9 requires all apps to run with HTTPS.
```

**Comment by grafixpress** [comment]
We always had a valid cert, and the issue is on all Android versions, and also on WebAp.
OK, I understand you don´t want to be bothered with this.
Thank you and have a nice day.

**Comment by Neustradamus** [comment]
I have seen several closing tickets, the 4.17.7 has a lot of solutions?

The problem, tickets are not commented here: https://github.com/Xtraball/Siberian/issues?q=is%3Aissue+is%3Aclosed.
