### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by userdevel2** [Xtraball/Siberian#742]
I have just received an email after submitting a build of my app with the following content:

"ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

Best regards,

The App Store Team"

How can I fix this error? Or is this a Siberian issue that we have to wait to be updated?

**Comment by SiberianCMS** [comment]
Already answered on the forums.

Normally this is just a warning for now, all the Ionic & Cordova teams are on it, we will have to await their official answers, but we will eventually upgrades apps.

We already use the WKWebView, but Cordova as lot of old references to UIWebView in the code, and the App Store does only a text search to warn users.

And please do not open any more issues on Github or your new account will be banned to.
Thanks.

**Comment by emiliodallatorre** [comment]
Hi,
I write to point out that, as of now, this is not a warning anymore, but an error.
Today my app got refused as:

> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

What should we try now?
