### ISSUE TITLE
[BACKOFFICE] URL Privacy Policy fix

### ISSUE THREAD

**Issue by Appteamit** [Xtraball/Siberian#743]
Entering the backoffice in the application the link to the privacy policy is incorrect:

/application/privacypolicy/id/4844866f755

instead it had to be:

/application/privacypolicy?id=4844866f755

To correct the problem, just edit the general.html file in line 83 from this:

 `<span><?php echo $this->getUrl("application/privacypolicy") . "/id/" ?>{{ tmp_application.key }}</span>`

in this way:
`<span><?php echo $this->getUrl("application/privacypolicy") . "/?id=" ?>{{ tmp_application.key }}</span>`

**Comment by SiberianCMS** [comment]
Nope, in fact it should be

`/application/privacypolicy/index/id/4844866f755`

We forgot the `index` part, we changed it from ?id= to id/ because Google Play do not like GET params.

But anyway, thanks for that, we will fix it for next updates.

**Comment by SiberianCMS** [comment]
Fixed in 4.17.9
