### ISSUE TITLE
[MEDIA - VIDEO] YOUTUBE NOT WORK

### ISSUE THREAD

**Issue by Appteamit** [Xtraball/Siberian#744]

**Comment by SiberianCMS** [comment]
@Spotcloudit please add/complete your description with examples, because to what we know, Media/Video youtube do work correctly!

So please, more complete description, with tests, examples, etc ... otherwise we'll close the ticket.

Thanks.

**Comment by Appteamit** [comment]
The Facebook function does not load if the ID page is entered. YouTube video feature does not show channel videos

**Comment by Appteamit** [comment]
even in the native woocommerce form, items cannot be deleted in the cart

**Comment by SiberianCMS** [comment]
Absolutely unrelated, please focus ...
