### ISSUE TITLE
Split this repository for a better management

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#746]
Can you split this repository in 2 parts?

For example, a dev must have 6 GB for work on this project, it is really big!

It will be better to have only the main code (not several same files, example: a script for duplicate files to compile process) and not compiled files.

**Comment by SiberianCMS** [comment]
On the earlier version the repository was split, but it was a hell to manage all resources.

Most of platforms/plugins already have their own individual repositories.

The repository will remain this way, 6GB is when you clone it with the full history, you can just clone the latest, or do a sparse clone.

Anyway if you really want to develop on Siberian it's better to have all the tools in the correct repository, everything is highly tied up

**Comment by Neustradamus** [comment]
6GB is the current "master" code.
It will be better to separate to be better, for all devs.
You will not forget changes like currently ;)
I can help you to improve this repository and have code and compiled code.
