### ISSUE TITLE
Getting 404 Error

### ISSUE THREAD

**Issue by GaneshKandu** [Xtraball/Siberian#748]
Hi,

I am getting 404 error after click on TOP LEFT logo

![Customize your app s style](https://user-images.githubusercontent.com/12833130/69127771-e7ffd580-0ad0-11ea-9b60-b6b682ee5619.png)

its redirecting on ```mydomain.com/admin/application/list```

![404  Page not found](https://user-images.githubusercontent.com/12833130/69127840-0f56a280-0ad1-11ea-8d0f-630f637d9169.png)

**Comment by SiberianCMS** [comment]
It's clearly a link for the MAE/PE editions, just ignore it for now, it's not relevant in SAE.

It should be the same link as "Dashboard" we will fix that asap.

**Comment by SiberianCMS** [comment]
Fixed in 4.18.0 to be released.
