### ISSUE TITLE
Ubuntu 18.04 error on java installation

### ISSUE THREAD

**Issue by bixmatech** [Xtraball/Siberian#749]
Hi,
I install siberiancms on my ubuntu 18.04, and followed this guide to install java and android sdk to be able to geenrate apk, but the command in the guide give error:
{
echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" | \
      tee --append /etc/apt/sources.list.d/jessie-backports.list > /dev/null
echo 'Acquire::Check-Valid-Until no;' > /etc/apt/apt.conf.d/99no-check-valid-until
apt update && apt install -t jessie-backports openjdk-8-jdk
}
the jessie backports not found

**Comment by SiberianCMS** [comment]
Documentation is for Debian, not for Ubuntu, I invite you to search on google 

https://www.google.com/search?q=unbuntu+18+install+jdk+1.8&oq=unbuntu+18+install+jdk+1.8&aqs=chrome..69i57.7166j0j7&sourceid=chrome&ie=UTF-8

Thanks.
