### ISSUE TITLE
Radio: Different Issues on Android and Apple

### ISSUE THREAD

**Issue by gonzoradio** [Xtraball/Siberian#751]
The radio player has cost me, literally, thousands of hours of headaches over the last 5 years.

The plugins and modules used for this are known to have issues and not work (i'm not an expert but that's what i've found personally, and read from others).

Why can't we just have a small player that sits below the admob slot?

As of Jan 29, 2020.....

Apple - no background audio working, no matter what i upload to testflight. i even put in a custom player from our streaming provider and no go on iphone but works great on android.

Android - buffer issues, buffer amount is hardcoded, buffer loops, opening our own html5 player from web now only opens in web browser INSIDE the app and thus no background audio when screen off or app minimized.  aac - radio can't hold stream  ,  mp3 - buffer looping and skipping

I'm hearing good things about replacing MediaPlayer with ExoPlayer.

Please!?!?!?!?!  I'll have to move to a new platform if this can't be solved, or lose my job (which i'm kinda ok with at this point).

Thanks!

**Comment by gonzoradio** [comment]
I've been following this thread, and the thread linked at the end by birdman, to try to solve this issue:
https://stackoverflow.com/questions/56508764/app-delegate-methods-arent-being-called-in-ios-13

Am I on the right track? Is the no background audio on iOS to do with SAE not being ready for Scene implementation?

I tried adding the following as suggested, but no luck:

ADD/Change...... CDVPlugin.m

 if (@available(iOS 13.0, *))
        {
           [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppWillTerminate:)
                                                        name:UISceneWillDeactivateNotification object:nil];
      
           [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppWillResignActive:)
                                                        name:UISceneWillDeactivateNotification object:nil];
           
           [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppDidBecomeActive:)
                                                        name:UISceneDidActivateNotification object:nil];

           [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppWillEnterForeground:)
                                                        name:UISceneWillEnterForegroundNotification object:nil];
        
           [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppDidEnterBackground:)
                                                        name:UISceneDidEnterBackgroundNotification object:nil];
           }
        else {
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppWillTerminate:)
                                                     name:UIApplicationWillTerminateNotification object:nil];
        
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppWillResignActive:)
                                                     name:UIApplicationWillResignActiveNotification object:nil];
        
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppDidBecomeActive:)
                                                     name:UIApplicationDidBecomeActiveNotification object:nil];

        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppWillEnterForeground:)
                                                     name:UIApplicationWillEnterForegroundNotification object:nil];

        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppDidEnterBackground:)
                                                     name:UIApplicationDidEnterBackgroundNotification object:nil];
        }

**Comment by SiberianCMS** [comment]
Our team is about to release the 4.18.17, the radio player has been reworked with native player instead of JS Audio API.
And the music controls are fixed too, along with the background audio for iOS (which wasn't working correctly due to the web audio api)

**Comment by gonzoradio** [comment]
(**crying**)
