### ISSUE TITLE
Mcommerce became inoperative after 4.18.14 update.

### ISSUE THREAD

**Issue by Knayz** [Xtraball/Siberian#753]
When I'm going to state path mmobilcart/mobile_sales_customer/index/value_id/... I get the next error in the console.

app.bundle-min.js?version=4.18.14.1586005938:1 TypeError: Customer.onStatusChange is not a function

I assume it happens becouse the factory method "onStatusChange" have been deleted in the file 
/var/apps/ionic/android/app/src/main/assets/www/js/factory/customer.js. But this method is steel used in the file 
/app/sae/modules/Mcommerce/features/m_commerce/js/controllers/sales/customer.js on the 9th line.

**Comment by SiberianCMS** [comment]
mmobilcart/mobile_sales_customer/index/value_id
This is not Mcommerce, it's MobilCart

However if you use "Mcommerce" 
You can just remove the line 9
/app/sae/modules/Mcommerce/features/m_commerce/js/controllers/sales/customer.js on the 9th line.

Customer.onStatusChange etc...

And do a "rebuild manifest", then you should be good.

A .15 will be rolled out by Monday to fix that issue.
