### ISSUE TITLE
Cross-Site Scripting 

### ISSUE THREAD

**Issue by farid007** [Xtraball/Siberian#754]
**Description**:- Siberian 4.18.10 and the previous version are vulnerable to cross-site scripting (XSS) attack. The application allows an attacker to execute arbitrary javascript code in 500.php
page `log` GET parameter. Due to this, an attacker can execute javascript code on the victim's browser and perform some action on behalf of the victim.

**Payload**:- `<img src=1 onerror=alert(document.domain)>`

**Page**:- errors/500.php.

![image](https://user-images.githubusercontent.com/28525518/78656385-efd7df00-78e4-11ea-9c17-ad6bea835c29.png)

**Vulnerable Code**:- 
(https://github.com/Xtraball/Siberian/blob/master/siberian/errors/500.php)

![image](https://user-images.githubusercontent.com/28525518/78656501-1f86e700-78e5-11ea-96b9-d8696d383f97.png)

As you can see in the code, only `<script>` is being filtered out.

**Remediation**:- htmlspecialchars($_GET['log']);  should be used.

**Comment by SiberianCMS** [comment]
This is already fixed in latest versions.

**Comment by Neustradamus** [comment]
@SiberianCMS: Are you sure?
I do not see in changelog.

**Comment by SiberianCMS** [comment]
@Neustradamus yes sure, we just don't write 100% of the changes in the regular changelogs.

Just check the new code, $_GET['log'] is now filtered to accept only the error__abc123.log files, nothing else can pass.

https://github.com/Xtraball/Siberian/blob/master/siberian/errors/500.php

**Comment by Neustradamus** [comment]
@SiberianCMS: Nice but 3 years after...

**Comment by farid007** [comment]
@SiberianCMS as it is a security vulnerability, this vulnerability must be registered in cve mitre database.

**Comment by Neustradamus** [comment]
@farid007: Can you report all CVEs? Thanks in advance.

**Comment by farid007** [comment]
@Neustradamus only vendor can directly request for cve in the GitHub 
https://help.github.com/en/github/managing-security-vulnerabilities/publishing-a-security-advisory#requesting-a-cve-identification-number

**Comment by Neustradamus** [comment]
@farid007: Not here but in CVE database: https://security.stackexchange.com/questions/107828/how-to-exactly-create-a-cve

Can you inform all CVEs not only this.

Thanks in advance.

**Comment by farid007** [comment]
@Neustradamus that link has information about how a vendor can request for CVE's directly from Github.

**Comment by Neustradamus** [comment]
@farid007: https://security.stackexchange.com/questions/107828/how-to-exactly-create-a-cve/107902#107902
