### ISSUE TITLE
Changelog problem when we update

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#756]
When we update, we can not click on other versions, we are blocked only on next version.
Can you solve it?

**Comment by SiberianCMS** [comment]
Can you upload a video or something to show the behavior?

**Comment by Neustradamus** [comment]
No I can not.

But it is easy:

Check update in backoffice

Look changelog part with all versions, you see by default the changelog of the next version that you want to install, but we can not see previous or next changelog.

**Comment by SiberianCMS** [comment]
You just have to click on the version number, and it will show it
https://streamable.com/w7w4hr

Anyway, you can also access them directly
https://updates02.siberiancms.com/release-notes/all/index.php

**Comment by Neustradamus** [comment]
It is strange, it does not work last time...

**Comment by Neustradamus** [comment]
@SiberianCMS: In the same time, can you reopen this ticket: https://github.com/Xtraball/Siberian/issues/703 and solve it?
Maybe I need to create a new?
