### ISSUE TITLE
Deployed on Synology DS918+, won't find JAVA

### ISSUE THREAD

**Issue by sebo-k** [Xtraball/Siberian#757]
Is there any way to change the PATH that Siberian is expecting Java to be in, since Synology has different file systems to other linux?

> By the way, my first problem deploying was that "unzip" is not used by Synology. So to install updates or packages, i had to modify the
> 
> > /app/sae/modules/Installer/Model/Installer/Module/Parser.php
> 
> to change the unzip lib with 7z. 
> 
> Changed this:
> `exec("unzip '{$this->_tmp_file}' -d '{$this->_tmp_directory}' 2>&1", $output);`
> to this:
> `exec("7z x '{$this->_tmp_file}' -o'{$this->_tmp_directory}' 2>&1", $output);`

**Comment by SiberianCMS** [comment]
JAVA is not necesarry anymore.
