### ISSUE TITLE
Always Xtraball SASE?

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#759]
I create a new ticket because closed tickets are not seen and forgotten.

I little search:
- https://github.com/Xtraball/Siberian/search?utf8=%E2%9C%93&q=Xtraball+SASE&type=

There are currently 5 "Xtraball SASE" in files:
- https://github.com/Xtraball/Siberian/blob/master/ionic/platforms/android/app/src/main/assets/www/js/filters/filters.js
- https://github.com/Xtraball/Siberian/blob/master/ionic/platforms/browser/www/js/filters/filters.js
- https://github.com/Xtraball/Siberian/blob/master/ionic/platforms/ios/www/js/filters/filters.js
- https://github.com/Xtraball/Siberian/blob/master/ionic/www/js/filters/filters.js
- https://github.com/Xtraball/Siberian/blob/master/siberian/var/apps/ionic/android/app/src/main/assets/www/js/filters/filters.js

An update is planned one day?

It was here:
- https://github.com/Xtraball/Siberian/issues/703

**Comment by SiberianCMS** [comment]
Due for 4.18.17
