### ISSUE TITLE
Before a new release, verify last module versions for security and bug corrections

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#761]
Can you update modules?

Examples:
- Music Controls 2 version 3.0.5: https://github.com/ghenry22/cordova-plugin-music-controls2/releases
- Social Sharing version 5.6.5: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/releases
- ...

**Comment by SiberianCMS** [comment]
SocialSharing was also update, as it got some references to the UIWebView that we had to get rid of.

https://github.com/Xtraball/SocialSharing

**Comment by Neustradamus** [comment]
@SiberianCMS: Can you update to the last:
- Music Controls 2 version 3.0.5 (14 May 2020): https://github.com/ghenry22/cordova-plugin-music-controls2/releases
- Social Sharing version 5.6.8 (24 May 2020) / 6.0.0 with Android X (24 May 2020): https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/releases

I think that I need to create new issues to do not forget...
