### ISSUE TITLE
New radio player Update Breaks aac ogg opus , listen live links sluggish

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/Siberian#762]
Hi This player was finally sorted out around a year ago and worked 100 per cent on all formats.
All it does now is play mp3 only with by todays Broadcasting standards is going backwards.

Can you please revert ASAP before everyone has no playing streams. as for now I am having to revert to 4.18.16.
If it works like it has done finally why break it again !!!

**Comment by SiberianCMS** [comment]
the Android MediaPlayer will be replaced with ExoPlayer in next update 4.18.19 probably

The native MediaPlayer on android is using okhttp and has very poor support, but that was the default in the cordova plugin we use, it works like a chamr in iOS for both streaming and files, but on android is horrible with streaming

Here is a list of what should be supported then

https://exoplayer.dev/supported-formats.html#progressive-container-formats

;)

**Comment by rogerdavis198** [comment]
When are we sorting this player out on Android as I am stuck on 4.18.16 so can not go forward as I have too many radio stations that use aac opus ogg etc so there is no way this can be left like this also 
we need to update the fruit machine apps for admod and can not do this due to screwing all the android players up, if we can not get this working properly you need to go back the original system as otherwise we are going backwards in audio terms as really you need to use the phones codecs as they are installed already, not third party ones.

**Comment by Neustradamus** [comment]
2.11.5: https://github.com/google/ExoPlayer/tags

**Comment by Loknath1076** [comment]
There's another problem with radio here in siberian cms sae. It takes long time to start streaming first of all and secondly when the streaming starts, it plays only for a few seconds and then it stops streaming for a second and then plays again and this very annoying thing goes on like that with the whole streaming and hard to listen music really. With music player, it happens the same.

**Comment by imediastars** [comment]
> There's another problem with radio here in siberian cms sae. It takes long time to start streaming first of all and secondly when the streaming starts, it plays only for a few seconds and then it stops streaming for a second and then plays again and this very annoying thing goes on like that with the whole streaming and hard to listen music really. With music player, it happens the same.

I have this problem with all my clients on Android devices. Playing radiostream it keeps buffering. iOS is doing fine...strange.

**Comment by SiberianCMS** [comment]
As long as we will not add a Codec SDK, there will always be player issues of any kind.

Adding a Codec SDK is approx. 50MB in size increase for APK, so we are balancing it for the future player, and maybe will have to make it optional, which by the way makes the build more complex.
