### ISSUE TITLE
New Radio Player (May2020) <sb-media-mini-player> covering content

### ISSUE THREAD

**Issue by gonzoradio** [Xtraball/Siberian#763]
Thanks for the improvements to the radio player!!

Huge difference now.

Only issue i'm having right now (besides colour) is that the mini-player covers the bottom content in the app.

Is there an easy fix for this?  I can edit in xcode and android studio for now if there is.

Thanks again!!

![app-issue](https://user-images.githubusercontent.com/5903657/83066899-c1989500-a033-11ea-8db0-9c7d204c7d01.jpg)

**Comment by SiberianCMS** [comment]
As long as we will not add a Codec SDK, there will always be player issues of any kind.

Adding a Codec SDK is approx. 50MB in size increase for APK, so we are balancing it for the future player, and maybe will have to make it optional, which by the way makes the build more complex.
