### ISSUE TITLE
exoplayer v2 released today

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/Siberian#764]
v2 released today which hopefully has opus aac ogg fixed in to pass these streams to the a android  phone codecs, can you update asap please

**Comment by Neustradamus** [comment]
2.11.5: https://github.com/google/ExoPlayer/tags

**Comment by Neustradamus** [comment]
2.11.7: https://github.com/google/ExoPlayer/tags

**Comment by SiberianCMS** [comment]
No idea if we will go exoplayer or vlc lib with opt-in for "media" apps.
