### ISSUE TITLE
Problems with push notifications.

### ISSUE THREAD

**Issue by Loknath1076** [Xtraball/Siberian#766]
Push notifications work but as it is seen there's an option to add image. Once an image is added and sent with the push, push message works fine but the images are not seen, instead of that, users see only a no image frame.

**Comment by SiberianCMS** [comment]
You may need to etup HTTPS/SSL correctly, remote images must be HTTPS to be displayed in push notifications

**Comment by SiberianCMS** [comment]
Close as stalled, not relevant anymore
