### ISSUE TITLE
Install : "Error" when connecting to database

### ISSUE THREAD

**Issue by Aeris1One** [Xtraball/Siberian#768]
Hi,
When the installer requests me to fill database infos it send me back a simple "Error" text, I used the install script from siberiancms.com for SAE, which downloaded the archive and extracted it.
Same error on two different Debian 9 Stretch servers with Yunohost installed.

Nginx logs: 
`[26/Jun/2020:12:08:23 +0200] "POST /installer/installation_database/check HTTP/2.0" 404 1022 "https://redacted.domain.com/"`

There's no /installer folder on my installation

**Comment by jebbrito** [comment]
também estou com o mesmo problema, no meu caso, aparece Erro em baixo do username.

**Comment by codebymike** [comment]
Right, a solution -

If you get this error, it means that your server's URL re-writes aren't working correctly. To fix this I did two things:

1) Edit your httpd.conf (or apache2.conf) files in your /etc/  directory - ensure that in the "/var/www" <Directory>, you edit  "AllowOverride None" to "AllowOverride All".

2) Copy and paste the contents from /.htaccess.txt into /.htaccess - and restart httpd/apache2

Everything should work correctly.

**Comment by SiberianCMS** [comment]
Close as stalled, not relevant anymore
