### ISSUE TITLE
Radio Player Android u/s

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/Siberian#769]
whats happening with this android player as it was supposed to be fixed in the last few updates, it is not passing the streams properly to the phones codecs, it just sits there buffering all the time apart from mp3 it useless, we can not update our apps to keep up with new SD regs due to this   can you get on this please as it was not broken before so if you are going to update something FFS make sure it works first rather than just changing the player without a thought for the android versions.

Cheers

**Comment by SiberianCMS** [comment]
As long as we will not add a Codec SDK, there will always be player issues of any kind.

Adding a Codec SDK is approx. 50MB in size increase for APK, so we are balancing it for the future player, and maybe will have to make it optional, which by the way makes the build more complex.
