### ISSUE TITLE
/!\ AdMob Consent SDK update (since 2020-02)

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#771]
Can you update AdMob Consent SDK 1.0.5 for iOS? "Consent SDK now uses WKWebView instead of UIWebView."
- https://github.com/googleads/googleads-consent-sdk-ios/releases
- https://github.com/googleads/googleads-consent-sdk-ios/releases/tag/v1.0.5

In the same time for Android (not the same version):
- https://github.com/googleads/googleads-consent-sdk-android

**Comment by SiberianCMS** [comment]
Already addresses in latest versions.
