### ISSUE TITLE
radio player

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/Siberian#772]
Hi the new radio player is not working on android properly (only mp3) can we please either fix it or create a second moduke based on the.original one that seems to not have all.the bugs that the new one has, it just does not work in any normal formats at all in android 10 and on 9 and bellow it just lags the data all the time so u get streams that are up to 10 15 mins behind the original.
I have backed this since the start and purchased lots of modules to help keep this alive and also the original  radio modules u had to purchase before which even though I paid for them are not in my account anymore , I have loads of streams and stations on my radio apps and its impossible to just update there apps and loose 90 per cent of there streams in the process, please can we have two modules so we can use the right one that work for mac or android as its simply a no no dropping the streams just because its easier to do your end fella.

Thank you

**Comment by imediastars** [comment]
Hi rogerdavis198,
I have clients who all complaint about Android radiostream is buffering a long time and sometimes endless... iOS apps are loading the streams really fast. Siberian told me there is nothing wrong but almost every single client complains about the Android version. Do you have the same? First I thought it had to do with my server, but how can iOS be super fast?

**Comment by rogerdavis198** [comment]
The mp3 ones or the Only ones that work out of the box If you use opus or ogg they take ages to stream, the aac ones are a no no on anything android, there must be a problem in the shell of siberian as the player is a google one so should work out the box. this is why I have been asking for the original player module to be added too as on android it works fine.
There is a big problem on android with the player as you say so this needs to really be sorted out as its not good for any of us and gives Siberian a bad Press too.

**Comment by SiberianCMS** [comment]
As long as we will not add a Codec SDK, there will always be player issues of any kind.

Adding a Codec SDK is approx. 50MB in size increase for APK, so we are balancing it for the future player, and maybe will have to make it optional, which by the way makes the build more complex.
