### ISSUE TITLE
PHP 8.x.x compatibility

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#774]
PHP 8.0.0 RC1 is here:
- https://www.php.net/

Please look to be ready when there will be PHP 8.0.0 final version.

**Comment by SiberianCMS** [comment]
There is no way we will do it in a short timeline, PHP 8 is still early and worst it breaks (well repair ...) lot of things, and lot of basic functions used in most frameworks will be affected ;)

We already supports up to PHP 7.3 and some modules do support php 7.4, but still, it's not only the Siberian core that matters, but all modules must also support PHP 8.0 so you see the picture.
