### ISSUE TITLE
Duplicating publisher-created users

### ISSUE THREAD

**Issue by flavianodelgado** [Xtraball/Siberian#781]
One problem when creating an account for another user through the editor:
When you create an account, you end up duplicating the created account and you get 2 equal accounts.

Even create 2 accounts with their own user IDs.

![124067396_3590630457624687_5974014231920178353_o](https://user-images.githubusercontent.com/74076908/98418260-40710f80-2061-11eb-9dad-b36846c0ff2c.jpg)
![124076447_3590607707626962_3838334913006601567_o](https://user-images.githubusercontent.com/74076908/98418265-41a23c80-2061-11eb-8f4b-60356dedd761.jpg)

**Comment by SiberianCMS** [comment]
Issue confirmed, team will release a fix asap.

**Comment by SiberianCMS** [comment]
Will be fixed in update 4.19.7.
