### ISSUE TITLE
Emails are overlapping on users

### ISSUE THREAD

**Issue by flavianodelgado** [Xtraball/Siberian#782]
In the backoffice, in the list of users the emails are overlapping and not from reading the emails.
I'm using a Full HD screen.
![2020-11-09 08_49_19-Siberian - Backoffice](https://user-images.githubusercontent.com/74076908/98539399-04a99600-226b-11eb-8aad-51e3df6e84e3.png)

**Comment by SiberianCMS** [comment]
Thanks for the report, we will check to increase the page & columns width first.
