### ISSUE TITLE
Background image not centered

### ISSUE THREAD

**Issue by paraglajder** [Xtraball/Siberian#784]
A video of the issue: https://www.dropbox.com/s/xa34fmwouteu222/48440295_752497958813715_7973564265818820134_n.mp4?dl=0

A client complained that the background image does not center on his device: https://www.gsmarena.com/huawei_y5_lite_(2018)-9501.php

To be fair, I also noticed this on some other devices which I don't have info on them. Any workaround or advice? Anders Jay Faust and friends you guys may want to look into this... In this particular image we see his background image behind the sliders which has the logo on top, the used image is attached here. On my device (Galaxy S8+) the image is centered properly.

**Comment by SiberianCMS** [comment]
Some devices may not be 100% compliant with CSS rules due to vendor versions of WebView, apart finding some custom css there is nothing we can do here.
