### ISSUE TITLE
Background images missing top section 

### ISSUE THREAD

**Issue by Skybod** [Xtraball/Siberian#785]
Since updating Siberian to the latest update - All the background (home) images do not reach the top of the iPhone - Images taken from iPhone 11 Pro Max 11 - Has affected all apps - before update was fine. 
![122596795_10158549757830673_1955621294203685148_o](https://user-images.githubusercontent.com/74318034/98843524-00d06c00-2443-11eb-9d39-4d419a06298e.jpg)
![122579148_10158549757815673_2235858407973050135_o](https://user-images.githubusercontent.com/74318034/98843530-02019900-2443-11eb-875a-061b9d61ba7f.jpg)

**Comment by SiberianCMS** [comment]
Check with latest updates, it's already fixed.
