### ISSUE TITLE
git clone takes too much time to clone Siberian

### ISSUE THREAD

**Issue by AnythingLinux** [Xtraball/Siberian#791]
Hello, we are having clone delay of Siberian. When we start clone it takes more then 24 hours.

**Comment by SiberianCMS** [comment]
Use the option `–depth 1`
The repository has a very large history and is quite heavy as of today, using `–depth 1` will clone only the "latest" commits/versions, without all the history (which you'll be able to fetch at any time if needed.

https://linuxhint.com/git-shallow-clone-and-clone-depth/

**Comment by SiberianCMS** [comment]
Result below

```
#dev test-depth  11:46 $ git clone --depth 1 https://github.com/Xtraball/Siberian.git siberian-d1
Cloning into 'siberian-d1'...
remote: Enumerating objects: 21540, done.
remote: Counting objects: 100% (21540/21540), done.
remote: Compressing objects: 100% (15709/15709), done.
remote: Total 21540 (delta 4889), reused 16130 (delta 3895), pack-reused 0
Receiving objects: 100% (21540/21540), 181.22 MiB | 2.62 MiB/s, done.
Resolving deltas: 100% (4889/4889), done.
Checking out files: 100% (24177/24177), done.
#dev test-depth  11:48 $ du -sh siberian-d1/
764M	siberian-d1/
```

Took only two minutes to clone
