### ISSUE TITLE
Audio page / playlist module translation and image bug

### ISSUE THREAD

**Issue by jcvikl** [Xtraball/Siberian#792]
![124843102_10158903797267290_7770509480680841238_n](https://user-images.githubusercontent.com/3075515/99898350-0e86bc80-2ca1-11eb-947c-afc2b7e69a79.jpg)

 In audio page / playlist module are 2 "bugs" - Listen to all is not under translation string. I dont know - perhaps is a picture. And music picture / icon into album is not correct on last step.

**Comment by SiberianCMS** [comment]
As long as we will not add a Codec SDK, there will always be player issues of any kind.

Adding a Codec SDK is approx. 50MB in size increase for APK, so we are balancing it for the future player, and maybe will have to make it optional, which by the way makes the build more complex.
