### ISSUE TITLE
Link function Done (x) and navigation buttons

### ISSUE THREAD

**Issue by Rakeshmvd** [Xtraball/Siberian#794]
In the iPhone app the X and navigation buttons of the Link function are not displayed correctly.

The Demo viewer (Admin interface) uses these classes
So these do not work: .iab-footer-nav,.iab-footer-button,.ion-ios-arrow-back,.ion-ios-arrow-forward,.ion-android-close,.inappbrowser-footer-close
But they do not work in iPhone.

It uses a completely different button layout: 
Demo viewer: Navigation buttons (left aligned) and [X](button) right aligned
iPhone app: "Done"(link, left aligned) and navigation buttons right aligned.

**Comment by SiberianCMS** [comment]
Demo viewer does it with HTML/CSS, but on iOS is a native view, so it's most probably an iOS layout issue here
