### ISSUE TITLE
JAVA: Not found

### ISSUE THREAD

**Issue by valneysl** [Xtraball/Siberian#796]
hello guys I installed the java on the vps but does not recognize the installation, would anyone know how I can solve it, my server and vps centos 64b whm

Thank you very much in advance

![gggg](https://user-images.githubusercontent.com/40365319/102702540-b95bad80-4242-11eb-9752-6a6f72991288.png)

**Comment by SiberianCMS** [comment]
Since latest updates we use exclusively the service apk generator, JAVA will not be required anymore, and so you can ignore this warning.
