### ISSUE TITLE
this request was blocked for security reason

### ISSUE THREAD

**Issue by leccyril** [Xtraball/Siberian#797]
Hello, 

i updated with last version siberian MAE. and now i could not use anymore the mobile fonction creation. Have you got an idea ? 

![image](https://user-images.githubusercontent.com/3234598/106384728-9e956080-63cc-11eb-89b9-e19b307c29d1.png)

thank you

**Comment by SiberianCMS** [comment]
Please update to 4.20.2 issue is solved.
