### ISSUE TITLE
Siberian installation Issues

### ISSUE THREAD

**Issue by asmamakhtout** [Xtraball/Siberian#799]
i come to install siberian cms using Wamp server and everything was good until this error on my screen,, and i don't know where it come from cause there's no like a line for this error or some to directly check pls if anybody can help cause all day i working to fix it but not yet find how

ERROR :: { "error": true, "message": "SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" }

i'm using windows 10, wamp server and PHP 8.0.2

thanks

**Comment by SiberianCMS** [comment]
@asmamakhtout please try again with latest version, there was a known issue during installation on the previous ones.
