### ISSUE TITLE
not showing default page except codes 

### ISSUE THREAD

**Issue by LinuxFintech** [Xtraball/Siberian#804]
I am trying to install this cms on Ubuntu 20.04 LTS but its not working. check attached

![Screenshot from 2021-04-20 23-46-40](https://user-images.githubusercontent.com/74146344/115441669-efca2900-a232-11eb-9d51-e70e5856f2e3.png)

**Comment by SiberianCMS** [comment]
It's not recommended to run it on localhost unless you want to do local development.
- Now
- You need to follow the server requirements **apache, php, mysql** or **nginx, php-fpm, mysql**
- Then you will see the installer starting

https://doc.siberiancms.com/knowledge-base/siberian-server-requirements/

Also as said, it's better to run it on a tiny VPS to start, with full ssh root access.
