### ISSUE TITLE
Installation ending error

### ISSUE THREAD

**Issue by christopherthomson** [Xtraball/Siberian#807]
I've got a fresh install of SiberianCMS that hangs at the 'Installation' stage of the installer. The ajax request to <domain>/installer/installation/end returns a 404 code and the application stalls with the message 'Installation ending' with the progress bar at 100%, as per the image below. There is no error output in /var/www/html/var/log/output.log. Can you please advise how to debug this? 
Thanks. 

<img width="1160" alt="Screen Shot 2021-08-19 at 8 17 31 PM" src="https://user-images.githubusercontent.com/1092387/130033426-b4c18f6f-3821-4b82-ba33-70afc3640312.png">

**Comment by christopherthomson** [comment]
Here is the console error:
<img width="1207" alt="Screen Shot 2021-08-20 at 9 21 43 AM" src="https://user-images.githubusercontent.com/1092387/130145956-b47dab66-d866-4e8e-819c-dbb7b46a5819.png">

**Comment by SiberianCMS** [comment]
Please check that you have followed the requirements & settings, this is most probably a configuration issue.

https://doc.siberiancms.com/knowledge-base/siberian-server-requirements/

**Comment by christopherthomson** [comment]
This was a configuration issue. I had to spend some time getting the php modules and php.ini settings right, and I had missed one of these. I also had some issues setting up MariaDB but after re-checking all the configuration it is now working (on Ubuntu 20.04). Thanks!
