### ISSUE TITLE
App stalls when loading

### ISSUE THREAD

**Issue by christopherthomson** [Xtraball/Siberian#810]
My app stalls when trying to load its menu upon startup. This occurs when running it in an emulator or on a test device. There are several error messages in Logcat in Android Studio, but the only one in the [myapp].androidoverview category is this:

E/WebViewAssetServer: Unable to open asset URL: http://localhost/favicon.ico 

Searching for references to this in the code I cannot identify the exact problem. Is this likely to be what is causing the app to stall? I'm also seeing errors to do with memtrack and tile memory limits. Under 'Project Errors' there are tons of 'Cannot resolve symbol' errors. I am using Android Studio default JDK 11.0.10. Android Studio suggests upgrading some modules, eg firebase-messaging --> v22; gms-play-services-ads --> 20.04. Not sure if any of these updates are needed. Any help finding the issue would be great, thanks.

**Comment by SiberianCMS** [comment]
Close as stalled, not relevant anymore
