### ISSUE TITLE
Missing icon during app creation causes other issues

### ISSUE THREAD

**Issue by claudioxerez** [Xtraball/Siberian#811]
I've just discovered why this string (Array ( [0] => Array ( [0] => fillBackground [1] => Array ( [0] => 15987699 ) ) ) Array ( [0] => Array ( [0] => fillBackground [1] => )appear.
In my PE when i create a new app, no app icon is assigned to it, as showed in image 1.

![Image 1](https://user-images.githubusercontent.com/77155281/139713741-23145c78-1a05-4c1a-b6a5-5622e1d71279.png)

Normal user behavior is working in newly app just created, but if user decides to create another app before working in last one it triggers this weird string to appear in app creation page, as showed in image 2.

![Image 2](https://user-images.githubusercontent.com/77155281/139713749-fcbcb8e0-f3b6-4da1-bb9b-993389a6e738.png)

I kindly ask you to test this in your PE to help me to confirm this is a "bug" only in my installation or a general "bug".
Just create a new app and see if icon is missing. If icon is not missing, bug is only im my platform. If icon is missing as showed in imagem 1, just create a new app and see if string appears in app creation page. I really appreciate your kindly help/test.

**Comment by claudioxerez** [comment]
I've commented lines 1503 and 1504 of file /app/sae/modules/Application/Model/Application/Abstract.php and "solved" issue, however i think this is just a quick solution. Please Dear Developers, take a look and provide a definitive fix.
Thank you.

**Comment by SiberianCMS** [comment]
This issue is already fixed in latest updates, closing*
