### ISSUE TITLE
Error updating to 4.20.23

### ISSUE THREAD

**Issue by Che-Guevara-PE** [Xtraball/Siberian#812]
Cron error and the preview screen in the editor is not displayed. I tried to restore the source code using Backoffice > Settings > Advanced > Tools but it didn't work.
Does anyone have a solution to this problem?

**Comment by SiberianCMS** [comment]
Check that your cron is running correctly

Restore app sources & Manifest are now done inside the cron (asap within the next minute) to prevent any timeout caused by the "web" services* (cron do not have any timeouts)

If your Pe still encounter issues after that, open a support ticket so our team will investigate on your server*

**Comment by Che-Guevara-PE** [comment]
**1. I have tested Cron on the server, it works fine. However in BackOffice, it shows not working message.
2. I have done Restore app sources & Manifest, but it doesn't work.
3. I've Checked Integrity, Outputs:**
**File Hash is different from manifest file:**
app/sae/design/desktop/backoffice/js/controllers/advanced.js
app/sae/design/desktop/backoffice/js/controllers/installer.js
app/sae/design/desktop/backoffice/template/page/layout.phtml
app/sae/design/desktop/flat/css/style.css
app/sae/design/desktop/flat/images/payment/method-2checkout.png
app/sae/design/desktop/flat/images/payment/method-offline.png
app/sae/design/desktop/flat/js/color-solver.js
app/sae/design/desktop/flat/js/features.js
app/sae/design/desktop/flat/js/js.js
app/sae/design/desktop/flat/layout/front.xml
app/sae/design/desktop/flat/template/page/layout/header_menu.phtml
app/sae/design/design-cache.json
app/sae/modules/Application/Form/NsDescription.php
app/sae/modules/Application/Model/Device/Ionic/Ios/Abstract.php
app/sae/modules/Application/controllers/Settings/AdvancedController.php
app/sae/modules/Application/resources/db/schema/application.php
app/sae/modules/Application/resources/design/desktop/flat/template/application/customization/design/colors/ionic/edit.phtml
app/sae/modules/Application/resources/design/desktop/flat/template/application/customization/features/list/options/li.phtml
app/sae/modules/Application/resources/design/desktop/flat/template/application/customization/features/list.phtml
app/sae/modules/Application/resources/design/desktop/flat/template/application/settings/advanced/index.phtml
app/sae/modules/Application/package.json
app/sae/modules/Backoffice/controllers/Advanced/ToolsController.php
app/sae/modules/Core/Model/Lib/Image.php
app/sae/modules/Core/Model/Lib/Uploader.php
app/sae/modules/Core/View/Default/Abstract.php
app/sae/modules/Front/Controller/Api/Base.php
app/sae/modules/Installer/controllers/InstallationController.php
app/sae/modules/System/resources/db/data/campaign.php
app/sae/modules/System/resources/design/desktop/backoffice/template/system/config/design.phtml
app/sae/modules/System/package.json
app/sae/modules/Template/resources/db/data/template.php
app/sae/modules/Template/package.json
app/Bootstrap.php
app/BootstrapCron.php
lib/Siberian/Color.php
lib/Siberian/Version.sample.php
lib/vendor/gregwar/image/Gregwar/Image/Image.php
var/apps/browser/js/utils/url.js
var/apps/ionic/ios/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork
var/apps/ionic/ios-noads/AppsMobileCompany.xcodeproj/project.pbxproj
var/apps/ionic/ios-noads/AppsMobileCompany/Bridging-Header.h
var/apps/ionic/ios-noads/www/dist/lazy/picker/picker.js
var/apps/ionic/ios-noads/www/dist/app.min.js
var/apps/ionic/ios-noads/www/dist/app.bundle.min.css
var/apps/ionic/ios-noads/www/templates/home/l10/modal.html
var/apps/ionic/ios-noads/www/templates/home/modal/view.html
var/apps/ionic/ios-noads/www/cordova_plugins.js
var/apps/ionic/ios-noads/config.bck.xml
var/apps/ionic/ios-noads/ios.json
File is missing.
app/sae/design/desktop/backoffice/js/controllers/advanced.js
app/sae/design/desktop/backoffice/js/controllers/installer.js
app/sae/design/desktop/backoffice/template/page/layout.phtml
app/sae/design/desktop/flat/css/style.css
app/sae/design/desktop/flat/images/payment/method-2checkout.png
app/sae/design/desktop/flat/images/payment/method-offline.png
app/sae/design/desktop/flat/js/color-solver.js
app/sae/design/desktop/flat/js/features.js
app/sae/design/desktop/flat/js/js.js
app/sae/design/desktop/flat/layout/front.xml
app/sae/design/desktop/flat/template/page/layout/header_menu.phtml
app/sae/design/design-cache.json
app/sae/modules/Application/Form/NsDescription.php
app/sae/modules/Application/Model/Device/Ionic/Ios/Abstract.php
app/sae/modules/Application/controllers/Settings/AdvancedController.php
app/sae/modules/Application/resources/db/schema/application.php
app/sae/modules/Application/resources/design/desktop/flat/template/application/customization/design/colors/ionic/edit.phtml
app/sae/modules/Application/resources/design/desktop/flat/template/application/customization/features/list/options/li.phtml
app/sae/modules/Application/resources/design/desktop/flat/template/application/customization/features/list.phtml
app/sae/modules/Application/resources/design/desktop/flat/template/application/settings/advanced/index.phtml
app/sae/modules/Application/package.json
app/sae/modules/Backoffice/controllers/Advanced/ToolsController.php
app/sae/modules/Core/Model/Lib/Image.php
app/sae/modules/Core/Model/Lib/Uploader.php
app/sae/modules/Core/View/Default/Abstract.php
app/sae/modules/Front/Controller/Api/Base.php
app/sae/modules/Installer/controllers/InstallationController.php
app/sae/modules/System/resources/db/data/campaign.php
app/sae/modules/System/resources/design/desktop/backoffice/template/system/config/design.phtml
app/sae/modules/System/package.json
app/sae/modules/Template/resources/db/data/template.php
app/sae/modules/Template/package.json
app/Bootstrap.php
app/BootstrapCron.php
lib/Siberian/Color.php
lib/Siberian/Version.sample.php
lib/vendor/gregwar/image/Gregwar/Image/Image.php
var/apps/browser/js/utils/url.js
var/apps/ionic/ios/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork
var/apps/ionic/ios-noads/AppsMobileCompany.xcodeproj/project.pbxproj
var/apps/ionic/ios-noads/AppsMobileCompany/Bridging-Header.h
var/apps/ionic/ios-noads/www/dist/lazy/picker/picker.js
var/apps/ionic/ios-noads/www/dist/app.min.js
var/apps/ionic/ios-noads/www/dist/app.bundle.min.css
var/apps/ionic/ios-noads/www/templates/home/l10/modal.html
var/apps/ionic/ios-noads/www/templates/home/modal/view.html
var/apps/ionic/ios-noads/www/cordova_plugins.js
var/apps/ionic/ios-noads/config.bck.xml
var/apps/ionic/ios-noads/ios.json

**What I need to do ?**
