### ISSUE TITLE
Installer stucks on Database connection

### ISSUE THREAD

**Issue by hassanayoub1985** [Xtraball/Siberian#813]
I am using aapanel with LNMP on ubuntu 20.04:
{
Nginx1.21
MySQL 5.7
PHP 7.3
}
Attached is the configuration of PHP.
The installer stucks on Database connection giving "Error":
POST https://DOMAIN/installer/installation_database/check 404

![2022-01-12_9-25-35](https://user-images.githubusercontent.com/26030596/149082567-801d912c-32c3-48d0-a9a9-c7f15da9fc6d.jpg)

**Comment by SiberianCMS** [comment]
Close as stalled, not relevant anymore
