### ISSUE TITLE
Cabride 5X notification is only going to one driver 

### ISSUE THREAD

**Issue by rpbfrank** [Xtraball/Siberian#844]
There is an issue on cabride 5X where the notification is going to only one driver per vehicle type selected by the passenger

so if you have a vehicle type a with 8 drivers under that vehicle type then only one driver gets the notification so there is no race

all vehicles are online and the are in the same location 

![image](https://github.com/Xtraball/Siberian/assets/61832641/d4b5cfa6-d5ae-457d-bc29-651840c15919)

![image](https://github.com/Xtraball/Siberian/assets/61832641/b26a2e9a-bc5c-43a7-a896-0f8184aceae7)

**Comment by rpbfrank** [comment]
can any one please fix the above please

**Comment by SiberianCMS** [comment]
Cabride is paid/commercial module, support is not provided here.
Here we focus only on Siberian open source platform.

**Comment by rpbfrank** [comment]
so who do i report to i am receiving no response from support not
***@***.***
