### ISSUE TITLE
Upgrade from PBL 5 to PBL 7

### ISSUE THREAD

**Issue by sl45sms** [Xtraball/Siberian#848]
By Aug 31, 2024, all new apps and updates to existing apps must use Billing Library version 6 or newer. 
so need to change from 5 to 7 at the following lines (assuming is that simple)

https://github.com/Xtraball/Siberian/blob/9e993d82457bb7412481d2cd0eb8238ff55e0b2d/ionic/platforms/android/project.properties#L27
https://github.com/Xtraball/Siberian/blob/9e993d82457bb7412481d2cd0eb8238ff55e0b2d/siberian/var/apps/ionic/android/project.properties#L27
https://github.com/Xtraball/Siberian/blob/9e993d82457bb7412481d2cd0eb8238ff55e0b2d/ionic/platforms/android/app/build.gradle#L314
https://github.com/Xtraball/Siberian/blob/9e993d82457bb7412481d2cd0eb8238ff55e0b2d/siberian/var/apps/ionic/android/app/build.gradle#L314

look for that matter to https://developer.android.com/google/play/billing/migrate-gpblv7

**Comment by SiberianCMS** [comment]
@sl45sms it is already available in 5.0.11 update.

https://github.com/Xtraball/Siberian/blob/release/5.0.11/ionic/platforms/android/project.properties#L45

**Comment by sl45sms** [comment]
Great, thanks, but what about "Production Ready" 4.20.44 branch, is there any plans to patch it? or should upgrade to 5 even if it is not marked as production?
