### ISSUE TITLE
PendingIntent with unspecified mutability

### ISSUE THREAD

**Issue by dusanpecko** [Xtraball/Siberian#849]
Hello 

Google sent me this, do you know what I should do? I have version 5.0.11

Pending intents mutability
If your app targets Android 12, you must specify the mutability of each PendingIntent object that your app creates. This additional requirement improves your app's security.
Test the pending intent mutability change
To determine whether your app is missing mutability declarations, look for the following lint warning in Android Studio:
Warning: Missing PendingIntent mutability flag [UnspecifiedImmutableFlag]
Unsafe intent launches
To improve platform security, Android 12 and higher provide a debugging feature that detects unsafe launches of intents. When the system detects such an unsafe launch, a StrictMode violation occurs.

**Comment by SiberianCMS** [comment]
No other reports with 5.0.11, maybe it was an older warning, google play takes some time to clear warnings after you update the AAB

Please confirm and close the issue if solved.
