### ISSUE TITLE
Warnings for onesignal privacy from Apple review

### ISSUE THREAD

**Issue by sl45sms** [Xtraball/Siberian#850]
i've got from apple the following:

ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/OneSignalCore.framework/OneSignalCore”, which includes OneSignalCore, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.

ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/OneSignalExtension.framework/OneSignalExtension”, which includes OneSignalExtension, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.

ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/OneSignalOutcomes.framework/OneSignalOutcomes”, which includes RxSwift, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.

**Comment by Neustradamus** [comment]
To follow this ticket.

**Comment by sl45sms** [comment]
Release 5.0.4 of onesignal adds the manifests https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1334
siberian uses 4.8.3 i beleive.

**Comment by Neustradamus** [comment]
@sl45sms: OneSignal Siberian fork is here:
- https://github.com/Xtraball/Onesignal

**Comment by sl45sms** [comment]
it will be fixed with 5.0.13, soon, so i've close this issue.
