### ISSUE TITLE
Licence server and apt generator is it down ? Mae and sae

### ISSUE THREAD

**Issue by rogerdavis198** [Xtraball/Siberian#860]
Hi both mae main and backup are showing red in the licence .
My text in SAE shows thekey fine ok ? Bit when you click to make an app it just does not make one , stays on  pending forever on.the back office,. At 3 this morning all.was fine , I have swapped all the sites to a different server and installed working backups from a week ago ,.also.the ip4 and same Mac have been transferred and it's still.the Same ????? Can you update us please. Thanks Les

**Comment by SiberianCMS** [comment]
This is the standard response when the licence server is down, nothing to worry about, it is internet, sometimes it is down.

**Comment by rogerdavis198** [comment]
Thank you for updating us,.is there not a check list of those servers to show if they up
Or down for maintenance?

⁣Get BlueMail for Android ​

**Comment by SiberianCMS** [comment]
We don't have a status page yet sorry, maybe something to think of!
